Cray-HPE/bos

- bos-reporter.spec
The bos-reporter-spire-agent's name was changed to
bos-state-reporter-spire-agent's because that is how I named it in the
OPA and Spire policies. The names all need to match, so I changed this
one.
CASMCMS-7355
Mug
This has been tested on Mug, which has a CSM-1.0 installation. I altered the OPA and Spire policies to let the bos-state-reporter through, and the BOS spire-agent on the compute node was able to get a JWT.
- Were continuous integration …
> CASMCMS-7355: Change name from bos-reporter to bos-state-reporter

- kubernetes/cray-bos/values.yaml.in
This corrects the value used by the bos chart in order to allow for a correct reference to the associated reference image and brings parity with the chart's associated annotations.
* Resolves and updates CASMCMS-7611
* build servers
Built the associated helm chart, downloaded the contents and verified the fix is in place.
> Casmcms 7611 redis fix for 1.2

- kubernetes/cray-bos/templates/clusterrolebinding.yaml
- kubernetes/cray-bos/templates/post-upgrade-job.yaml
- kubernetes/cray-bos/templates/role.yaml
- kubernetes/cray-bos/templates/rolebinding.yaml
- kubernetes/cray-bos/templates/serviceaccount.yaml
- src/server/bos/v1_v2_migration.py
BOS V2 stores its session templates in a redis database. This mod
copies the existing V1 SessionTemplates from their storage in etcd to
redis. It copies them, but does not delete them from etcd. This
preserves the ability to rollback to the V1 release and retain access to
the session templates.
It contains a migration script that is run as a Helm hook on upgrade.
This migration script migrates BOS V1 session templates from the
V1 etcd database to the V2 redis database.
The V1 session templates are pruned, so that they only contain
content appropriate for a V2 session template.
Any V2 session templates that exist will not be overwritten during
migration. This allows migration to be done repeatedly without
risk of losing a V2 session template.
Because the migration job reads directly from …
> Copy V1 session templates from etcd to V2's redis database

- update_external_versions.conf
The fix for [CASMCMS-7753](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7753) is incomplete for csm-1.2. Specifically, it fixed boa v1.2, but bos v1.10 points to boa v1.1 (which does not have the fix). This PR just updates bos v1.10 to point to boa v1.2, thus picking up this fix.
[CASMCMS-7753](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7753)
I tested this on surtur and validated that it resolves the boa bug blocking the barebones boot test.
There may be risks with the fix for CASMCMS-7753 -- I didn't look into the details of the fix. But since its PR got approved I assume that whatever risks it entailed were deemed acceptable. This PR just makes the fix present in csm-1.2.
- [N/A] Version number(s) incremented, if applicable
- [N/A] Copyrights updated
- [N/A] …
> CASMCMS-7760: Use boa v1.2

- Jenkinsfile.github
- Makefile
- bos-reporter.spec.in
Build the BOS rpms for the SLES15SP2 and SLES15SP3 distributions.
The COS compute node images are SLES-based, so we need to build the
rpm with the distribution environment.
To prevent the accumulation of files from previous stages in the build,
clean up the contents of the RPM build directories after publishing its
contents. This does clean-up ahead of time, so that SLES15SP2 files are not
included with SLES15SP3 files.
Publish the Helm chart and Docker image ahead of the RPMs.
This helps speed up development because developers are less interested in
the RPM results.
Resolves: CASMCMS-7802
Build and Hela
Hela
Test by building as well as downloading the rpms and installing them.
- Were …
> Casmcms 7794 csm 1.2

- kubernetes/cray-bos/values.yaml.in
This corrects the value used by the bos chart in order to allow for a correct reference to the associated reference image and brings parity with the chart's associated annotations.
* Resolves and updates CASMCMS-7611
* build servers
Built the associated helm chart, downloaded the contents and verified the fix is in place.
> Update image reference in values.yaml for associated BOS redis image.

- kubernetes/cray-bos/Chart.yaml.in
- kubernetes/cray-bos/values.yaml.in
Update the database image from redis:5.0-alpine3.12 to redis:5.0-alpine. This less specific tag allows use of more recent alpine base images that are still being patched for security vulnerabilities. The current version uses alpine:3.15 and has the security issues resolved.
* Resolves [CASMCMS-7823](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7823)
* Change will also be needed in `config-framework-service`
* Merge with `https://github.com/Cray-HPE/config-framework-service/pull/36`
* `Mug`
I verified the new image is clean using the SNYK scanner. After building a new version of cray-cfs-api using the new database image, I updated the deployment on Mug, verified the db was working correctly, then rolled back to the original version.
- Were the …
> Update to patched version of redis image.

- api/openapi.yaml.in
- src/bos/operators/session_cleanup.py
- src/bos/operators/utils/clients/bos/base.py
- src/bos/operators/utils/clients/bos/options.py
- src/bos/operators/utils/clients/bos/sessions.py
- src/bos/server/controllers/v2/options.py
This mod introduces a new BOS v2 operator that allows automatic cleanup of completed sessions thats are of a certain age (and older). The default for this configuration value is 7d; after 7d, completed sessions based on session status start time, are purged from BOS. Purging a completed session does not have any direct effect on associated components (desired state for nodes in a session may still be set).
* Resolves [CASMCMS-7892](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7892)
* mug
Deployed the full set of changes and issued several dummy sessions and tested the following conditions:
- disabled (no sessions deleted)
- nominal (older sessions (in testing, 1m) being deleted
- No cull …
> CASMCMS-7892

- src/bos/server/controllers/v2/components.py
Component records will have timestamps deleted from them, as 'timestamp'
is not a defined property in the openapi spec.
* …
> Update Controller get code references to dynamically strip

- Dockerfile
- Jenkinsfile.github
- requirements.txt
- update_external_versions.conf
Use the correct location for Alpine Docker image. Only pin it to the
major version, so it will float and grab the highest minor and patch
versions.
At the same time, remove the reference to arti.dev.cray.com. The python modules will now get pulled directly from public repos which both protects us from hpe network domain changes and gets us a step closer to building through github action
* Resolves [CASMCMS-7974](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7974)
* Resolves [CASMCMS-7972](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7972)
STILL NEEDS TESTING
_How were the changes tested and success verified? If schema changes were part of …
> CASMCMS-7974: Update Alpine Docker image and dev.cray.com addresses.

- src/bos/reporter/etc/bos-reporter.service
- src/bos/reporter/status_reporter/__main__.py
When a non-default value is passed in to bos-status-reporter through
/proc/cmdline, it is first parsed as a datetime.timedelta object. On
computes, BOS automatically injects this value onto /proc/cmdline. When
this happens, BOS assumes that a non-default value is to be used, so it
needs to convert this default (4h) into a period of time, in seconds,
that are required to sleep before reporting.
Unfortunately, a multiplicative set operation was being used in addition
to a conversion from datetime.timedelta to total_seconds, which
increased the overall reporting window by an additional multiplicative
factor. As a result, BOS-status-reporter was sleeping way too long to
report overall boot artifacts when this value was specified.
This mod corrects the problem and adds additional logging …
> CASMCMS-8023: Correct the way BOS Status Reporter Sleeps

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/server/controllers/v1/sessiontemplate.py
- src/bos/server/v1_v2_migration.py
This modifies the migration script to keep a "deprecated" version v1 sessiontemplates rather than removing them entirely.
This also fixes a couple of related issues including removing the length requirement on sessiontemplate names and restoring the bypassed templateURL code for v1. 
* Resolves CASMCMS-7924
* Resolves CASMCMS-8010
* Resolves CASMCMS-8080
* Groot
- Removed a v2 copy of a template and re-ran the migration script so that template was re-added as both a v2 and v1_deprecated version
None
> Update v1/v2 migration to retain v1 copy of sessiontemplates

- CHANGELOG.md
- kubernetes/cray-bos/Chart.yaml.in
- kubernetes/cray-bos/values.yaml.in
- update_versions.conf
Using the new ".stable" file generated alongside the usual .version files, this PR modifies the repo path for the cray-bos images in the Chart and values files. For the images not build in this repo, this PR leaves them hardcoded as stable.
None beyond verifying that the unstable chart that was built correctly points to unstable cray-bos images.
```
$ grep stable cray-bos/Chart.yaml cray-bos/values.yaml
cray-bos/Chart.yaml:      image: artifactory.algol60.net/csm-docker/stable/cray-boa:1.2.82
cray-bos/Chart.yaml:      image: artifactory.algol60.net/csm-docker/unstable/cray-bos:2.1.0-CASMCMS-8088.1_87697b9
cray-bos/Chart.yaml:      image: artifactory.algol60.net/csm-docker/stable/docker.io/library/redis:5.0-alpine3.12
cray-bos/values.yaml:  repository: …
```
> CASMCMS-8088: Generate valid unstable chart artifacts

- kubernetes/cray-bos/values.yaml.in
Increases the resource limit to a point where it no longer was throttling on a test machine.
* Resolves CASMCMS-7885
* Groot
Changed the limit and watched the graphs on grafana to watch for throttling
None
> CASMCMS-7885: Increase operator resource limits to avoid throttling

- CHANGELOG.md
- Dockerfile
- Jenkinsfile.github
- update_external_versions.conf
Changing the reference from arti.dev.cray.com to
arti.hpc.amslabs.hpecorp.net
* Resolves [CASMCMS-7972]
Everything built just fine for BOS and BOA in the pipline.
I built the BOS testing image locally. It built.
I downloaded and examined the BOS SLES15SP4 RPM. It looked fine.
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
Low
> CASMCMS-7972: Update to use internal HPE network

- src/bos/server/__main__.py
Fixes a regression that causes v1 sessiontemplate records to not load correctly.
* Resolves CASMCMS-8085
* Fanta
- Found previously failing templates, and loaded them successfully with this change.
None
> CASMCMS-8085: Fix error loading old v1 session status records

- CHANGELOG.md
- src/bos/server/controllers/v2/components.py
Defined EMPTY_BOOT_ARTIFACTS by importing it.
Without this import, the applystaged operation failed on a reboot.
Do not check the BSS token if it is empty. This prevents spurious
warnings.
Add better error logging.
* Resolves CASMCMS-8157
* groot
On groot, I tested staging information for Node 4 and then applying that staged information. The node successfully rebooted using it. Before, it had failed to reboot.
- Were continuous integration tests run? If not, why? No. 
- Was upgrade tested? If not, why? Yes.
- Was downgrade tested? If not, why? 
- Were new tests (or test issues/Jiras) created for this change?
Low.
> CASMCMS-8157

- CHANGELOG.md
- gitInfo.txt
- kubernetes/cray-bos/Chart.yaml.in
- kubernetes/cray-bos/templates/_helpers.tpl
- kubernetes/cray-bos/templates/post-upgrade-job.yaml
- kubernetes/cray-bos/templates/role.yaml
- kubernetes/cray-bos/values.yaml.in
- src/bos/server/v1_v2_migration.py
- update_versions.conf
Migration job should talk only to new cray-bos pods
The migration Helm hook needs to only talk with the newly spun up
pods. It should not talk with the pods that are spinning down
because their V1 endpoints talk with the old etcd database. We need
the V1 endpoints to be talking with the new redis database, so that
the session templates are migrated to the redis database. Talking
to the etcd DB means the session templates will be stored there, but
will be inaccessible because the new endpoints ignore etcd. In effect,
upon upgrade the session templates look like they disappeared instead
of migrating to the new database.
To ensure it is talking to the new pods, the Helm hook job needs to
identify them by their labels. It then gets one of the new pods'
IPs and talks only to it.
Side note, the …
> Casmcms-8101

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/server/controllers/v1/healthz.py
- src/bos/server/controllers/v2/healthz.py
Allows both versions of the API to use the same openapi schema for status reporting in a db agnostic way.
* Resolves [CASMCMS-8163](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8163)
I built out the resultant change via our openapi, both through the pipeline and locally and examined the contents of the generated connexion model for healthz reporting. The updated image contains a model that has a db_status field instead of an etcd_status field.
Code was then deployed onto groot to ensure the healthz endpoints were functioning appropriately.
* `groot`
> CASMCMS-8163: Make v1 and v2 report db_status instead of <db kind>_status

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/operators/utils/clients/s3.py
- src/bos/server/test/test_status_controller.py
Correct spelling errors / typos in the repo. They have not caused any reported problems, but we may as well fix them. No need to make a manifest PR, though -- these can just get picked up the next time we make a release.
One of the typos was in code, but it is test code. It seems like the function in question must not have been called, as it surely would have failed.
> CASMCMS-8041: Correct minor spelling errors

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/operators/utils/clients/bos/options.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/controllers/v2/options.py
Introduces new behavior and option for electively tweaking how BOS performs staging operations. The new option 'clear_stage' allows users to elect the original behavior of removing staged boot information from a given component during the apply stage operation. This new option defaults to 'False', allowing BOS to retain the staged artifact information during a nominal boot. Set this option to true to globally revert to the old behavior.
* Resolves [CASMCMS-8158](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8158)
* Change will also be needed in `develop`
Locally built and verified image; then deployed to 1.3 system.
* Tested, and reverted from`drax`
Verified through API that the new option was settable and retrievable through exec action into the pod …
> Casmcms-8158

- CHANGELOG.md
- src/bos/operators/status.py
Gets all the components from CFS. We used to get only the components of interest, but that caused an HTTP request that was longer than uwsgi could handle when the number of nodes was very large.
Requesting all components means none need to be specified in the request.
* Resolves CASMTRIAGE-4246
* `Shandy`
I restarted the BOS status operator using the new image. It no longer encounters the request too large errors that it did before. Everything is unstuck, and BOS V2 is working!
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test …
> CASMTRIAGE-4246: Request state of all CFS components, not some

- CHANGELOG.md
- src/bos/server/controllers/v2/sessions.py
Fixes an error when reporting the components associated with an error in v2 extended session status.
* Resolves CASMCMS-8270
* Locally
Setup a test locally since it's difficult to reproduce with a large system to cause errors on.
None
> CASMCMS-8270: Fix v2 session status error reporting

- CHANGELOG.md
- src/bos/operators/power_on.py
Retry writing the BSS token to the BOS database. The connection to the database can be lost due to infrequent use. Retrying overcomes this difficulty.
(cherry picked from commit 442201340c2515cf03b67912c0512d5ab7bb2cda)
* Resolves CASMCMS-8275
* `Shandy`
The problem was that the power-on operator was losing its connection to the Redis database where it mapped BSS tokens to boot artifacts. This connection would be disrupted after fifteen minutes of inactivity. The remedy was to do a retry. I patched the code and restarted the BOS power-on operator. Then, I did three reboots of different nodes with fifteen minute pauses …
> CASMCMS-8275: Retry writing the BSS token to the BOS database.

- CHANGELOG.md
- src/bos/server/controllers/v2/options.py
Increases the timeouts that v2 uses to determine when to retry and give up on nodes that are booting or powering off.  Nodes can still complete faster than this.  These values are also configurable if sites wish to decrease them.
This addresses some issues seen on Shandy while testing where nodes were not completing in time and a large portion of the system was failing to boot as a result.
* Resolves CASMCMS-8279
* Shandy
These values were deployed and several sessions were run.
None
> CASMCMS-8279: Increase v2 timeouts

- CHANGELOG.md
- src/bos/operators/session_setup.py
Fixes a bug where applying a staged shutdown was trying to write an empty bss token to the staged state area.
* Resolves CASMCMS-8284
* Frigg
Ran a staged shutdown session and confirmed the correct data was in the component after the session was started.
None
> CASMCMS-8284: Fix v2 state generation for staged shutdown

- CHANGELOG.md
- src/bos/operators/utils/rootfs/__init__.py
Omitting these tags allows sessiontemplates to provide a static root=<value> within a bootset paramters field without duplication.
There is discrepancy between usecases for Mercury and Shasta/COS over the use of special cased fields that string together the root=<value> fields. In Shasta, this field is specialized and allows for additional calculations, however, for Mercury, these extra steps are not needed.
A recent change went in to allow this to work for COS' dracut modules to correctly parse this field, but these changes are not compatible with the way that Mercury interprets the same fields.
Solution: Because mercury (and future others) do not require preconfig or preprocessing of root filesystems, we do not require the use of rootfs_provider and rootfs_provider_passthrough fields. …
> CASMCMS-8300: Allow BOSv2 To omit rootfs provider tags

- CHANGELOG.md
- src/bos/server/controllers/v1/status.py
Fixes the "complete" and "in_progress" fields for BOS v1 session status
* Resolves CASMTRIAGE-4669
* Mercury
Ran a session and watched the status while running and after completion.
None
> CASMTRIAGE-4669: Fix sessions status complete and in_progress values

- CHANGELOG.md
- api/openapi.yaml.in
No content changes, just linting of some of the language in the text fields of the openapi spec file. The only non-language linting is removing the trailing / from one of the url fields, as this was flagged by an openapi linter as being bad practice.
[Corresponding craycli PR](https://github.com/Cray-HPE/craycli/pull/67) to make the same changes in the Cray CLI, as well as a few CLI-specific BOS language fixes.
Very very low risk. Just changes to language in text fields.
> CASMCMS-8381: Linting of language in openapi spec file

- CHANGELOG.md
- kubernetes/cray-bos/values.yaml.in
Adds the disaster recovery information for etcd to the chart values
* Resolves CASMCMS-8539
* Tested by Brad Klein on Ashton
None
> CASMCMS-8539: Add disasterRecovery section for etcd operator values

- src/bos/operators/utils/rootfs/cpss3.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/controllers/v2/sessions.py
Fixes the apply staged endpoint so that nodes that don't belong to the tenant are returned in the "ignored" section.
Also fixes issues with multi-tenancy around session status and a recent import bug caused by code reorganization.
* Resolves CASMCMS-8452
* Mug
Ran through session status, staging sessions, applying staged sessions, shutdown and boot with two tenants.
None
> CASMCMS-8452: Return non-tenant nodes with the ignored nodes

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/operators/filters/base.py
- src/bos/operators/filters/filters.py
- src/bos/operators/session_setup.py
- src/bos/server/controllers/v2/sessions.py
Add an 'include_disabled' option to control whether nodes that are
disabled in the Hardware State Manager (HSM) are included in a BOS
session. This option is used for the BOS V2 sessions endpoint for
POST requests.
* Resolves [CASMTRIAGE-5255](issue link)
I tested this in vshasta v2 on dorian.
* `Dorian`
I sent two shutdown requests for two nodes, 1 and 2. 
In the first request, I had node 2 disabled, and include_disabled was False. Node 2 was not part of the session.
In the second request, I had node 2 disabled, and include_disabled was True. Node 2 was part …
> Casmtriage 5255 support 2.0

- CHANGELOG.md
- Jenkinsfile.github
- Makefile
- bos-reporter.spec.in
Change the bos-reporter rpm to be designated as `noarch`. This is required for the aarch64 support and to remove the redundant x86_64 rpm.
* Resolves [CASMCMS-8517](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8517)
* Merge with `https://github.com/Cray-HPE/csm/pull/2158`
> CASMCMS-8517: rpm noarch for bos-reporter

- CHANGELOG.md
- constraints.txt
- src/bos/operators/base.py
- src/bos/operators/power_on.py
Updates the power-on operator to pre-set the last action so that there is no longer a window of time between calling capmc and setting the last action, which was leading to an incorrect status.
* Resolves CASMCMS-8609
* crossroads
Tested shutdown, boot and reboot sessions successfully.
None
> CASMCMS-8609: Update power-on operator to pre-set the last action (1.3/1.4)

- CHANGELOG.md
- src/bos/operators/base.py
- src/bos/operators/power_on.py
Updates the power-on operator to pre-set the last action so that there is no longer a window of time between calling capmc and setting the last action, which was leading to an incorrect status.
* Resolves CASMCMS-8609
* crossroads
Tested shutdown, boot and reboot sessions successfully.
None
> CASMCMS-8609: Update power-on operator to pre-set the last action

- CHANGELOG.md
- api/openapi.yaml.in
* [CASMCMS-8561](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8561): The BOS API spec says that Version objects have fields major, minor, and patch which are of type integer. However, it actually returns string representations of those integers.
* [CASMCMS-8575](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8575): The BOS API spec says that Link objects only have two possible fields -- href and rel. However, in practice additional fields are included for BOS v1 session links. This PR creates a new V1SessionLink definition that includes these additional fields.. Also updated the BOS v1 session status definition to note that the v1 session ID is in UUID format.
This PR just updates the spec to reflect these facts. It does not make any change to BOS itself -- just updates the …
> CASMCMS-8561/CASMCMS-8575: Update Swagger spec to match actual behavior

- CHANGELOG.md
- api/openapi.yaml.in
2. [CASMTRIAGE-5367](https://github.com/Cray-HPE/bos/pull/134)
3. [CASMCMS-8576](https://github.com/Cray-HPE/bos/pull/126)
4. [CASMCMS-8572](https://github.com/Cray-HPE/bos/pull/127)
5. [CASMCMS-8577](https://github.com/Cray-HPE/bos/pull/128)
6. [CASMCMS-8447](https://github.com/Cray-HPE/bos/pull/130) (this one) …
> CASMCMS-8447: Update API spec to show that GET of session templates can return v1 or v2 templates

- CHANGELOG.md
- api/openapi.yaml.in
2. [CASMTRIAGE-5367](https://github.com/Cray-HPE/bos/pull/134)
3. [CASMCMS-8576](https://github.com/Cray-HPE/bos/pull/126)
4. [CASMCMS-8572](https://github.com/Cray-HPE/bos/pull/127)
5. [CASMCMS-8577](https://github.com/Cray-HPE/bos/pull/128) (this one)
6. [CASMCMS-8447](https://github.com/Cray-HPE/bos/pull/130) …
> CASMCMS-8577: Update the spec to accurately reflect what is returned when creating or getting a BOS v1 session

- CHANGELOG.md
- api/openapi.yaml.in
2. [CASMTRIAGE-5367](https://github.com/Cray-HPE/bos/pull/134)
3. [CASMCMS-8576](https://github.com/Cray-HPE/bos/pull/126)
4. [CASMCMS-8572](https://github.com/Cray-HPE/bos/pull/127) (this one)
5. [CASMCMS-8577](https://github.com/Cray-HPE/bos/pull/128)
6. [CASMCMS-8447](https://github.com/Cray-HPE/bos/pull/130) …
> CASMCMS-8572: Update API spec to reflect that creating a BOS v1 session requires operation AND templateName/templateUuid

- CHANGELOG.md
- api/openapi.yaml.in
2. [CASMTRIAGE-5367](https://github.com/Cray-HPE/bos/pull/134)
3. [CASMCMS-8576](https://github.com/Cray-HPE/bos/pull/126) (this one)
4. [CASMCMS-8572](https://github.com/Cray-HPE/bos/pull/127)
5. [CASMCMS-8577](https://github.com/Cray-HPE/bos/pull/128)
6. [CASMCMS-8447](https://github.com/Cray-HPE/bos/pull/130) …
> CASMCMS-8576: Update API spec to reflect that GET /v1/session returns list of IDs not sessions

- CHANGELOG.md
- api/openapi.yaml.in
2. [CASMTRIAGE-5367](https://github.com/Cray-HPE/bos/pull/134) (this one)
3. [CASMCMS-8576](https://github.com/Cray-HPE/bos/pull/126)
4. [CASMCMS-8572](https://github.com/Cray-HPE/bos/pull/127)
5. [CASMCMS-8577](https://github.com/Cray-HPE/bos/pull/128)
6. [CASMCMS-8447](https://github.com/Cray-HPE/bos/pull/130) …
> CASMTRIAGE-5367: Update API spec to use valid ECMA 262 regular expressions

- CHANGELOG.md
- src/setup.py.in
The BOS server is now running under Python 3.11. This PR updates the BOS server module's setup file to specify that it is made for Python 3.11.
* Resolves [CASMCMS-8628](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8628)
Make sure the build doesn't fail.
Very low risk. We're already using Python 3.11.
> CASMCMS-8628: Update BOS server setup file from Python 3.6 to 3.11

- CHANGELOG.md
- Dockerfile
- src/setup.py.in
For the support/2.0 branch, we don't want to unexpectedly start using a new Alpine (and possibly therefore Python) version. New patch versions is fine, but we want to avoid even new minor versions, as that is what caused a recent problem on a customer system.
This PR pins the Alpine version to 3.18 (which is the version currently being used in this branch)., 
Make sure the build works.
Low risk -- it's already using this Alpine version -- this just pins it so rebuilds will also use it.
> CASMCMS-8628/CASMCMS-8631: Indicate Python version, pin Alpine version

- CHANGELOG.md
- api/openapi.yaml.in
It turns out that one of my API spec changes caused the problem reported in [CASMTRIAGE-5404](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5404). This is because the server code imports the automatically generated V1Session object, and my updated spec did not have the templateUuid field in that object.
The spec was internally consistent, but I overlooked this dependency inside the code itself.
The simplest fix is to put that field back into the definition in the spec. The downside is that this makes the spec slightly less accurate. It isn't wrong, it's just that my original changes were more specific about the cases when you could possible see a BOS v1 session with the templateUuid field in them. This version leaves open the possibility that any BOS session could have that …
> CASMTRIAGE-5404: Merge definitions of V1Session and V1SessionByTemplateName to avoid session creation error using templateUuid

- CHANGELOG.md
- src/bos/server/controllers/v1/session.py
Starting in CSM 1.2, it is not possible to create a BOS session such that the internal BOS session object contains the `templateUuid` field. That field is still allowed when creating templates, but it is only used if a `templateName` field is not specified, and either way the `templateUuid` field itself is not saved into the BOS database. (It is possible for BOS sessions to exist in the DB that still have `templateUuid` fields, but only if they were created prior to CSM 1.2 and never deleted).
I made two recent PRs that related to creating BOS v1 sessions:
* [CASMCMS-8577: Update the spec to accurately reflect what is returned when creating or getting a BOS v1 session](https://github.com/Cray-HPE/bos/pull/128)
* [CASMCMS-8572: Update API spec to reflect that creating a BOS v1 session …
> CASMTRIAGE-5404: Avoid V1Session objects with template_uuid fields

- CHANGELOG.md
- Dockerfile
We are currently using v6.4.0 of the generator. It looks like v6.6.0 is the latest release. I think we should at least update to v6.5.0, because the release notes for that indicate that it improves support for `anyOf` and `allOf` OpenAPI keywords, and we're now making more use of those.
This PR just bumps the generator version used for generation in the Dockerfile.
I ran the cmsdev regression tests and they passed.
Low risk -- just a small version bump on the API generator.
> CASMCMS-8644: Move from v6.4.0 to v6.6.0 of openapi-generator

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/server/controllers/v2/components.py
Pulls in a fix so that actual_state is not updated by state-reporters during the setup steps of a new session, which could interrupt reboots to the same set of artifacts.
* Resolves CASMCMS-8613
* Ashton
This is a scale system issue, so I had scripts mimic the issue and validate that the correct error was returned.
None
> CASMCMS-8613: Fix patching of component actual_state

- CHANGELOG.md
- api/openapi.yaml.in
It looks like some of the session template naming restrictions were actually being enforced. Kind of. The regular expression fields were being enforced, but they were also written so that they would mistakenly match any session template name. When we fixed the regular expressions in the API spec to fix [CASMTRIAGE-5367](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5367), it then prevented session templates from being created which did not fit the corrected regular expression.
We had already planned to modify the spec to remove these restrictions and state that they are only recommendations ([CASMCMS-8649](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8649)), but now that appears to be a more urgent need. This PR does that just for the template name field. CASMCMS-8649 will also …
> CASMINST-6451: Relax BOS session template name restrictions and convert the restrictions into recommendations

- CHANGELOG.md
- api/openapi.yaml.in
The BOS API is going to rely on a header parameter to receive the tenant name, but that is not currently captured in the BOS API spec. This PR is an attempt to correct that.
* Resolves [CASMCMS-8659](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8659)
I deployed this on wasp and verified that the cmsdev suite executed without error for BOS and I was still able to create sessions and session templates.
Hopefully low risk.
> CASMCMS-8659: Document tenant header parameter in API spec

- CHANGELOG.md
- src/bos/common/tenant_utils.py
- src/bos/server/redis_db_utils.py
Fixes v1 session template creation.  Connexion was passing arguments to the controller function according to the function's signature, but the v1_multitenancy decorator was altering the signature.  Using functools preserves the signature of the underlying function.
* Resolves CASMTRIAGE-5525
* Fanta
Successfully ran the barebones boot test, which had previously been failing.
None
> CASMTRIAGE-5525: Fix decorators to preserve function signatures

- CHANGELOG.md
- api/openapi.yaml.in
Another linting pass over the BOS API spec:
* Corrects some outdated or incorrect information that made it through the previous sweeps, as well as doing more general language linting.
* Added the "deprecated" specifier in places where it made sense, instead of just relying on it in the description.
* Refactored some repeated definitions to use common schemas instead
Somehow I overlooked this in my spate of changes before. The spec says that creating a V1 session template returns a session template object, but it actually just returns the template name. 
```text
ncn-m001:~/mitch/c # cray bos v1 sessiontemplate create --name harfharf --file v1temp.json
harfharf
```
This PR updates the spec to reflect this.
None of this should have any functional changes at all – no API schemas were changed …
> CASMCMS-8661/CASMCMS-8667: API spec linting & corrections

- CHANGELOG.md
- api/openapi.yaml.in
- constraints.txt
- requirements.txt
- src/bos/server/controllers/v1/sessiontemplate.py
The `templateUrl` option when creating session templates has been broken since BOS started using non-root users in its containers (CSM 1.2). Given that it has been broken for that long without it being reported by anyone, presumably it is not being used. Therefore this PR removes it from the spec and removes the associated code.
Note that the code is further simplified by the fact that 'name' is a required field for session templates, and since this function does make use of the API model in that case, it will throw an exception if one is provided with no name. Therefore this PR also removes the superfluous conditional checking for the name.
* Resolves [CASMCMS-8674](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8674)
* [support/2.0 backport](https://github.com/Cray-HPE/bos/pull/159)
* …
> CASMCMS-8674: Remove templateUrl option for creating v1 session templates

- CHANGELOG.md
- src/bos/operators/actual_state_cleanup.py
Fixes an issue where the actual state cleanup operator was trying to clear a configuration field which is not actually stored in the actual state.  This switches to using the common definition for clearing the actual state
* Resolves CASMCMS-8532
* Dorian - updated the actual state for component and verified that the cleanup operator zero'd the state correctly.
None
> CASMCMS-8532: Fix actual state cleanup operator patching

- CHANGELOG.md
- api/openapi.yaml.in
First, this PR does a bit of further minor tidying of the API spec:
* Includes a commit which adds example values to some fields which lacked them
* Includes a commit which refactors common endpoint parameters into **components/parameters**
Second, the main purpose of this PR:
As we discussed previously, this adds recommended limits to a number of fields in the API spec, noting that they will be enforced in the future.
In all cases I tried to err on the side of allowing rather than forbidding. I am open to imposing additional character restrictions on any of the string fields, or reducing the length limits I chose.
It turned out that there was no convenient RegEx to say "regular ASCII character that isn't something crazy like backspace", which is why you don't see more **pattern** fields …
> CASMCMS-8649: Update API spec with recommended field limits on user-supplied values

- CHANGELOG.md
- api/openapi.yaml.in
Baby step #1 -- add back "deprecated" tag to objects which previously only noted it in their description texts. This should only impact the API docs that are generated and not any of BOS itself.
> Updated the API spec to make use of the OpenAPI deprecated tag

- CHANGELOG.md
- api/openapi.yaml.in
Targeted baby-step PR two:
- Update spec to correctly tell you what you get back when creating a V1 template (the name of the template).
> CASMCMS-8667: Update API spec to reflect fact that creating v1 template returns name of template on success

- CHANGELOG.md
- api/openapi.yaml.in
Final targeted support/2.0 PR -- this one adds back the upcoming field restrictions, adding them to the description text fields. No new actual limits are imposed by this PR. Also, no schemas are created to avoid repeated statements of these limits.
> Add upcoming field limits into API spec description fields

- CHANGELOG.md
- api/openapi.yaml.in
In the context of boot sets, node lists are required to be non-empty. This is not a new requirement in the API spec.
However, I accidentally imposed this requirement on V1 status update requests as well, and those ARE allowed to have the node lists be empty.
This PR makes two different node list schemas, one which is allowed to be empty and one which is not. For boot sets, it uses the one which requires an element. For the status updates, it uses the one which allows it to be empty. This will make things be back to the way they were before my recent PR, which caused this problem.
* Resolves [CASMTRIAGE-5575](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5575)
* Problem injected by [CASMCMS-8661](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8661)
> CASMTRIAGE-5575: Update API spec to reflect that node lists are permitted to be empty in some circumstances

- CHANGELOG.md
- api/openapi.yaml.in
When creating a new BOS v2 session, the end_time and error status fields begin with null values. This contradicts the spec, which says they take string values. OpenAPI offers the "nullable" option to indicate when such fields may take null values. These fields should be marked as such.
Changing this will have no functional impact on BOS.
* Resolves [CASMCMS-8697](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8697)
* develop branch PR forthcoming
> CASMCMS-8697: Mark status/error and status/end_time string fields as nullable in API spec

- CHANGELOG.md
- constraints.txt
BOS builds are failing due to the problem documented in [CASMCMS-8713](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8713). Moving to PyYAML 6.0.1 resolves the problem. This PR moves PyYAML from 6.0 to 6.0.1. The only difference between these two versions is to force PyYAML to build using a Cython version < 3.0, which is what 6.0 was doing up until very recently (when Cython 3.0 was released and wrought havoc). This has no functional impact to PyYAML itself, nor to BOS, but builds will fail without this PR.
A similar change is being made to a number of CSM repositories that are similarly affected.
> CASMCMS-8713: Bump PyYAML from 6.0. to 6.0.1 to prevent build issue

- .gitignore
- CHANGELOG.md
- Makefile
- constraints.txt.in
- update_external_versions.conf
- update_versions.conf
Now that `update_external_versions` handles Python modules, this update this repo to use it in order to grab the latest patch version of the `liveness` Python module.
(This was prompted by my noticing some cases in other repos where we are using outdated versions of our Python modules)
> CASMCMS-8722: Use update_external_versions to get latest patch version of liveness Python module

- CHANGELOG.md
- api/openapi.yaml.in
When making the test changes for [CASMCMS-8553](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8553), I discovered that in some contexts, BOS populates the `tenant` field with a null value (as opposed to an empty string value). 
```text
ncn-w003:/tmp/zebrafish # cray bos v2 sessions list --format json
```
```json
[
{
"components": "",
"include_disabled": false,
"limit": "",
"name": "caa05de4-5c27-477a-98fb-8f330c87690d",
"operation": "boot",
"stage": false,
"status": {
"end_time": null,
"error": null,
"start_time": "2023-08-04T16:58:09",
"status": "pending"
},
"template_name": "test3",
"tenant": null
},
{
"components": "",
"include_disabled": false,
"limit": "",
"name": "8d217f08-a306-44ee-b82c-976a660eaf7c",
"operation": "boot",
"stage": false,
"status": {
"end_time": null,
"error": …
```
> CASMCMS-8753: Update API spec to reflect that BOS sometimes populates the 'tenant' field with a null value

- CHANGELOG.md
- src/bos/common/utils.py
- src/bos/operators/base.py
Introduced global read timeout values for undetected half open connections caused by network reconfiguration or istio interruptions. Now all connections that take longer than 10 seconds to send any data are considered dead. This prevents us from waiting indefinitely for APIs that will never respond over an undetected closed connection.
Added logic to automatically terminate zombie operators that have their main threads terminate (for whatever reason). When a main thread exits, the heartbeat thread will notice and exit as well.
* Resolves [CASMCMS-8752](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8752)
* Change will also be needed in corresponding release/1.5
Simulated do-no-harm testing on local dev system; these changes are identical to some that went in to cfs-state-reporter and the …
> feature/CASMCMS-8752: Increased resiliency settings for read and heartbeat

- CHANGELOG.md
- Jenkinsfile.github
When having to jump through a lot of hoops to get the new SLES15 SP5 RPMs added to various manifests, Rusty asked if we could instead build our RPMs as "noos", to avoid having to do this in the future. I think most CMS RPMs fit the criteria. While some do have SOME level of OS dependence (like relying on systemctl), all OSes that we ever intended to support with these RPMs are going to meet that requirement.
For bos-reporter in particular, there is no reason not to make it OS independent.
This has the additional benefit of allowing us to make our Jenkins build jobs much shorter and more parallelized.
> CASMCMS-8691: Build bos-reporter RPM as noos

- CHANGELOG.md
- src/bos/server/migrations.py
Fixes a bug where repeating the database key migration, caused by migrating from a BOS version with multi-tenancy to a newer version of BOS, was causing session templates and sessions to dissapear.
* Resolves CASMCMS-8756
* Mug
Tested repeated upgrades
None
> CASMCMS-8756: Fixed repeated database key migration

- CHANGELOG.md
- src/bos/operators/session_setup.py
- src/bos/operators/utils/clients/hsm.py
Fixes the architecture handling to correctly handle what is expected from HSM and fixes the component querying so that HSM is not queried with an empty list.
* Resolves CASMTRIAGE-5820
* fearne (Virtual Shasta)
- Ran a test session that was previously failing
None
> CASMTRIAGE-5820: Fix for HSM query handling

- CHANGELOG.md
- bos-reporter.spec.in
The bos-reporter RPM relies on spire-agent in order to function. This PR updates the spec file for the bos-reporter RPM to reflect this requirement.
> CASMCMS-8770: List spire-agent as a required package for bos-reporter

- CHANGELOG.md
- src/bos/server/controllers/v1/sessiontemplate.py
- src/bos/server/controllers/v2/sessiontemplates.py
We have decided to change BOS in CSM 1.5 so that even when using the v1 endpoint to create session templates, BOS will always create a v2-compatible session template. This PR contains two commits:
1. In order to help with this, this PR updates the v1 session template template to no longer include v1 fields that will just end up being stripped when the template is created.
2. This PR also updates some of the example fields being returned to be more useful to users (by populating them with typical defaults or with values closer to the expected actual field formats). This change is for both the v1 and v2 session template templates.
I don't intend to merge this to master and tag it yet -- I intend for this to go in alongside the other BOS changes we're planning.
> CASMCMS-8797: Update BOS session template templates

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/server/controllers/v1/sessiontemplate.py
- src/bos/server/migrations.py
This modifies the v1 session template create function. The function starts as usual by validating that it was passed in a valid v1 session template object. But then I made the following changes:
1. The function then strips away from the input data the v1-specific fields (both from the main session template and from each boot set).
2. The function then strips away the "name" field from the input data, because it is required to be there for v1 session template creation, but is read-only for v2 session templates.
3. Then follow basically the same code as from the v2 session template create function, except that the tenant will always be an empty string, and the function on success returns 201 and the name of the template (so that it still follows the v1 API spec).
I have tested this on mug …
> CASMCMS-8799: Create v2-compatible session templates with v1 endpoint

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/server/controllers/v1/sessiontemplate.py
- src/bos/server/migrations.py
We have decided to change BOS in CSM 1.5 so that even when using the v1 endpoint to create session templates, BOS will always create a v2-compatible session template.
[CASMCMS-8797](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8797) [modified the v1 session template template endpoint](https://github.com/Cray-HPE/bos/pull/210) so that it returns a v2-compatible template.
This PR updates the API spec to reflect the fact that BOS will never return to the user a v1-format session template. It will still allow them to be created, but all session templates it outputs will be v2-compatible.
This PR does not change BOS itself to do this – that is being done [with this PR](https://github.com/Cray-HPE/bos/pull/212). Thus I do not plan to merge this PR until that one is also approved.
None of the …
> CASMCMS-8798: Update BOS API spec to reflect internal change to all v2-compatible session templates

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/server/controllers/v1/sessiontemplate.py
I overlooked a couple of deprecated V1 fields in my changes for [CASMCMS-8799](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8799). Specifically, while I covered `cfs_url` and `cfs_branch` at the session template level, I did not address the deprecated fields within the `cfs` field of the session template.
This PR takes care of that, as well:
* Makes a few updates to the description fields of the API spec to explicitly state which fields are automatically removed in this version of BOS.
* Removes the now-superfluous read-only `links` field from the V1SessionTemplate schema, since that schema is now never used to return information from BOS, and is only used to validate session templates being created by the user. Thus, read-only fields will never exist. (plus, I don't think we ever …
> CASMCMS-8806: Remove deprecated cfs fields from v1 session templates

- CHANGELOG.md
- setup.py
- src/bos/operators/base.py
- src/bos/operators/power_off_forceful.py
- src/bos/operators/power_off_graceful.py
- src/bos/operators/power_on.py
- src/bos/operators/power_operator_base.py
- src/bos/operators/status.py
- src/bos/operators/utils/clients/capmc.py
When CAPMC returns errors, handle them and disable the associated nodes instead of panicking and halting all forward progress.
Added some new classes.
Handle troublesome CAPMC errors that don't point fingers and indentify which nodes experienced the errors.
If CAPMC returns an error that cannot be associated with an individual node, then reissue the CAPMC command for each individual component. Under that condition, Any components returning an error is guaranteed to be the cause of the error, so they are associated with the error and disabled in order to not cause BOS to attempt to retry them.
As a consequence of handling CAPMC-returned errors, the power operators need to be able to disable nodes. When they receive errors from CAPMC, they can declare those nodes disabled.
Create a …
> CASMCMS-8754: Make BOS V2 status operator resilient to power errors

- CHANGELOG.md
- src/bos/operators/session_setup.py
- src/bos/operators/utils/clients/hsm.py
When there are no nodes in a session due to them being eliminated for one reason or another, ensure that hsm.py's get_components method returns the expected type of object.
In the case that there are no nodes within a session to act upon, raise an exception, so that the session is marked as having failed and has its error attribute filled in appropriately.
* Resolves [CASMCMS-8830](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8830)
* `Mug`
I created BOS sessions containing no nodes and saw that the sessions had an error saying they contained no nodes.
- Were the install/upgrade-based validation checks/tests run …
> CASMCMS-8830: Fix return type error

- CHANGELOG.md
- src/bos/operators/power_off_forceful.py
- src/bos/operators/power_off_graceful.py
- src/bos/operators/power_on.py
- src/bos/operators/session_setup.py
To truly allow the 'include_disabled' nodes capability, the power operators cannot filter out the disabled nodes. This mod removes that filter. The session's 'include_disabled' nodes attribute will be used in the session setup operator to decide whether the nodes will be enabled in BOS or not. If disabled nodes are not included, then they will never be enabled and never acted upon. Thus, including them in the query to HSM will not hurt anything because they will never be acted upon.
When filtering nodes by architecture, do not also filter by whether the nodes are enabled in HSM. This is done at a later step in the process. Doing this earlier thwarts the later filtering.
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug …
> CASMCMS-8835: Do not prematurely filter out disabled nodes

- CHANGELOG.md
- src/bos/operators/session_setup.py
Filtering on architecture was throwing an error when filtering an empty list because HSM doesn't return the same data structure when you ask for an empty list of nodes.
* Resolves CASMTRIAGE-6176
Mug
Ran a session with no valid nodes and validated the output
None
> CASMTRIAGE-6176: Fix error when filtering for architecture on an empty node list

- CHANGELOG.md
- src/bos/server/controllers/v2/sessions.py
When the v2 sessions database was modified to use tenant-aware keys, the delete_v2_sessions function was overlooked. It still used the session name as the database key. As a consequence, it no longer deleted any sessions when it was called, regardless of the filters that were set.
This PR corrects the above, and also makes a couple of other small adjustments to that function:
* Modifies it so that it more closely mirrors the behavior of the regular delete_v2_session function (in terms of its order of operations -- deleting the status DB entry first, then the regular DB entry).
* Removes redundant calls to the get_tenant_from_header function
* Relocates code from the try: clause which is not really part of it (since the try clause is only looking for exceptions related to parsing the …
> CASMCMS-8865: Modify delete_v2_sessions function to use tenant-aware DB key

- CHANGELOG.md
- src/bos/operators/session_setup.py
- src/bos/server/controllers/v2/components.py
Sessions that specify nodes in the node list that are not available to that tenant will now fail with an appropriate error message and the list of bad nodes.
* Only nodes in the node_list are considered.  groups and roles containing other nodes are still considered valid and will just filter out the invalid nodes
* There is no error if the limit includes invalid nodes.  The limit is a way of filtering down nodes and cannot add nodes so it is not considered to be requesting a specific node.
Also fixes some grammar in other error messages
* Resolves CASMCMS-8451
* mug
Tested sessions with valid and invalid nodes
None
> CASMCMS-8451: Fail sessions that specify nodes that are not in the tenant

- CHANGELOG.md
- Dockerfile
- kubernetes/cray-bos/Chart.yaml.in
BOS builds started failing when it started using Alpine 3.19 as the base image instead of Alpine 3.18. This was happening because the Dockerfile just said to use the most recent v3 Alpine. If we eventually want to move up to Alpine 3.19 or later, we can do so after we resolve the build issues.
This PR also changes the version of the etcd base chart, to address [CASMPET-6876](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6876).
* Resolves [CASMCMS-8880](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8880) (which is the BOS portion of [CASMPET-6876](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6876).)
* [CSM 1.5 backport PR](https://github.com/Cray-HPE/bos/pull/238)
* The Alpine issue exists in other CMS repos as well. I'm going to handle it in those repos using …
> CASMCMS-8880: Update etcd base chart version; Pin Alpine version

- CHANGELOG.md
- Dockerfile
PEP-668 allows file systems to be labeled as 'externally managed'. Pip will see this label and refuse to install into any directory thusly labeled. The idea is to prevent pip from installing its packages into a directory that the operating system owns.
To install files correctly, I utilize a virtual environment and install them into there. The PATH variable is modified to point first at this virtual environment.
uwsgi is installed into this virtual environment and run out of there rather than being run from the operating system.
* Resolves [CASMCMS-8879](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8879)
* Change will also be needed in `master`
_List the environments in …
> CASMCMS-8879: Fix build issue caused by PEP-668

- CHANGELOG.md
- Dockerfile
The python virtual environment change should enable us to move ahead to later versions of Alpine 3 beyond 3.18. These later versions should not cause problems due PEP-668 because the resolution to CASMCMS-8879 fixed that issue. Pinning the version to 3.18 prevented us from encountering the PEP-668 problem because it pinned to a version of Alpine that did not introduce the issue.
* Resolves [CASMCMS_8879]
* Mug
* The first test was that this built successfully. That is probably all that was needed, but I went further.
* I tested this on `Mug` by installing it and seeing that the BOS operators all launched successfully. …
> CASMCMS-8879: Unpin the Alpine version from 3.18 back to 3

- CHANGELOG.md
- src/bos/operators/session_setup.py
- src/bos/operators/utils/boot_image_metadata/s3_boot_image_metadata.py
- src/bos/operators/utils/rootfs/__init__.py
- src/bos/operators/utils/rootfs/baserootfs.py
- src/bos/operators/utils/rootfs/factory.py
- src/bos/operators/utils/rootfs/sbps.py
Scalable Boot Provisioning Service (SBPS) support added
To support the Scalable Boot Provisioning Service (SBPS), two new
classes were created, SBPSProvider and a  base class BaseRootfsProvider.
* Resolves [CASMCMS-8778](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8778)
* mug
I booked some nodes with the following session template.
{
"boot_sets": {
"name_your_boot_set": {
"etag": "",
"kernel_parameters": "console=ttyS0,115200 bad_page=panic crashkernel=512M hugepagelist=2m-2g intel_iommu=off intel_pstate=disable iommu.passthrough=on modprobe.blacklist=amdgpu numa_interleave_omit=headless oops=panic pageblock_order=14 rd.live.ram=1 rd.neednet=1 rd.retry=10 rd.shell split_lock_detect=off systemd.unified_cgroup_hierarchy=1 …
> Casmcms 8778 Add Scalable Boot Provisioning Service (SBPS) support aka iSCSI support

- CHANGELOG.md
- CASMCMS-8879: Fix build issue caused by PEP-668
- CASMCMS-8879: Unpin the Alpine version from 3.18 back to 3
- Release BOS version 2.13.0
* Resolves [CASMCMS-8879]
* `Mug'
The build built in the pipeline. I installed it on a system and the operators worked.
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
_Are there known issues with these changes? Any other special …
> Release 2.13.0

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/server/controllers/v2/sessions.py
The current API (in both spec and actual behavior) allows the v2 sessions PATCH call to modify pretty much any field of the session. This is not the intended behavior. In practice, this call should only be used by BOS internally, and even then it should only ever be modifying the `components` and `status` fields.
This PR modifies the API spec to reflect this, as well as the actual API behavior.
I have also made a PR to the CLI (linked in next section) to remove the sessions update path, as it is not intended to be used by administrators.
* Resolves [CASMCMS-8905](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8905)
* [Cray CLI PR](https://github.com/Cray-HPE/craycli/pull/135)
I tested the change on mug and verified that changing other fields no longer works, but that the status and …
> CASMCMS-8905: Removed unintended ability to update v2 session fields other than status and components

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/server/controllers/v2/components.py
This PR addresses a few issues with BOS v2 components PATCH/PUTs:
1. Currently if a PATCH request is made to the `v2/components` endpoint using a filter that includes a component ID that does not exist, BOS will respond with an internal server error. This is because on this code path, it does no validation to ensure that the IDs actually exist. This is different from if the user sends a PATCH request which is just a list of components. In that case, if any one of the components has a nonexistent ID, BOS will gracefully respond with a 404.
2. When making a PATCH request to the `v2/components` endpoint using a filter, the BOS server code requires that this filter have exactly one non-empty property specified -- either `session` or `ids`. However, this requirement is not communicated by the …
> CASMCMS-8916: BOS v2 components patch/put: Fix bug, validate inputs, make spec more precise

- CHANGELOG.md
- src/bos/operators/filters/filters.py
- src/bos/operators/utils/clients/cfs.py
We're doing BOS v2 scale testing on UKMet and noticed that some CFS v2 components queries were constantly being retried. I was able to reproduce it outside of BOS and discovered that the queries were too large for CFS to handle. This PR modifies BOS so that it chunks up its CFS component requests into smaller bunches. It was already doing that for its patch requests, but not the gets.
I'm tested this on mug and wasp. I am using a modified version of the patch with the batch size much smaller, to force the new code path.
> CASMCMS-8941: Break up large CFS component queries to avoid failures

- CHANGELOG.md
- src/bos/operators/session_setup.py
When the BOS v2 session-setup operator is operating on a session with a large number of nodes, it ends up making a lot of S3 calls unnecessarily. The calls to S3 depend only on the boot sets in the session, but the current code makes the calls once per node, even if all the nodes belong to the same boot set.
This PR changes it so that the boot sets are parsed for this just once, rather than once per node.
I've tested these changes on wasp.
https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8944
Backports:
https://github.com/Cray-HPE/bos/pull/260
https://github.com/Cray-HPE/bos/pull/261
> CASMCMS-8944: Reduce superfluous S3 calls during BOSv2 session creation

- CHANGELOG.md
- src/bos/operators/base.py
- src/bos/operators/utils/clients/capmc.py
This PR addresses two problems:
1. In the base BOS operator, when it is detecting and acting on components, up front it gets a list of components and returns if it is empty. But then it filters that list to remove any components which have exceeded their retry limits. After doing that, it does not check again to see if the list is empty, even though it may be. This PR adds a check after that filtering.
2. The CAPMC client `power` function is supposed to return a `CapmcXnameOnOffReturnedError` object. The code in the `_power_components` method in the base power operator depends on this, because it assumes the returned object will have an `error_code` attribute. However, if an empty list of nodes is passed into the `power` function, then it returns a tuple of an empty set and an empty …
> CASMCMS-8946: Correct two problems with operating on empty node lists

- CHANGELOG.md
- src/bos/operators/base.py
CSM 1.5.1 backport of https://github.com/Cray-HPE/bos/pull/263 (only the base operator part, since the CAPMC client is gone in this BOS version)
> CASMCMS-8946: Update base operator to handle case where all nodes to act on have exceeded their retry limit

- CHANGELOG.md
- src/bos/operators/power_off_forceful.py
- src/bos/operators/power_off_graceful.py
- src/bos/operators/power_on.py
- src/bos/operators/session_setup.py
- src/bos/operators/utils/clients/hsm.py
- src/bos/server/controllers/v2/sessions.py
Specifically, this backports the following:
* [CASMCMS-8617](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8617): Remove failed nodes from session status phase ([source commit](https://github.com/Cray-HPE/bos/commit/c7dcfead50c5991d179c9a31f3568d083abf7372))
* [CASMCMS-8614](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8614): Remove on_hold components from session status phases ([source commit](https://github.com/Cray-HPE/bos/commit/a8d596b6e77c34da366a88664374ff8a49392b0d))
* [CASMCMS-8830](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8830): Fix return type error ([source commit](https://github.com/Cray-HPE/bos/commit/ffd36b5791bcac5806e9591d7efad709a359759b))
* [CASMCMS-8835](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8835): Do not prematurely filter out disabled nodes …
> CASMCMS-8948: Backport selected BOSv2 fixes/improvements

- CHANGELOG.md
- src/bos/operators/status.py
- src/bos/operators/utils/clients/capmc.py
- src/bos/operators/utils/clients/cfs.py
This PR consists of 3 parts:
1. The `_run` method of the status operator always ends up doing nothing if there are no enabled components. But currently it still ends up querying both CAPMC and CFS before it figures this out. This PR changes it so that if there are no enabled components, it just DEBUG logs that fact, and returns.
2. Add a check to the beginning of the CAPMC `status` function for the case when it is called with no nodes listed. Similar code already exists in the `power` function, and this PR basically makes equivalent code for `status`. The "empty" return values are slightly different, since the expected return values of the functions differ, but otherwise it's the same thing.
3. Adds similar checks to the beginning of a few CFS client functions. Pretty much every other …
> CASMCMS-8952: Improve handling of no-op situations

- CHANGELOG.md
- src/bos/operators/utils/clients/pcs.py
This just replaces the GET call to PCS with an equivalent POST call. The POST operation is being added with [CASMHMS-6156](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6156).
I tested this on mug with my PCS changes from [CASMHMS-6156](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6156) and it all works swimmingly. I can confirm from the BOS logs that it's happily using the POST operation.
> CASMCMS-8951: Use POST instead of GET when querying PCS for node power status

- CHANGELOG.md
- src/bos/operators/utils/clients/cfs.py
When reviewing the BOS v2 code as part of the UKMet scale testing, I noticed that the CFS patch function is less efficient than it could be. Most notably, for its [components update request](https://github.com/Cray-HPE/config-framework-service/blob/7efb10b44cd9c58ebdd4671e6f03f5922bf20d03/api/openapi.yaml#L130) it chooses to use the [component state array format](https://github.com/Cray-HPE/config-framework-service/blob/7efb10b44cd9c58ebdd4671e6f03f5922bf20d03/api/openapi.yaml#L762), even though that is only efficient when each component is being patched with different data. BOS always patches all of the components in the request with the same data, so it makes more sense to use the [component patch filter format](https://github.com/Cray-HPE/config-framework-service/blob/7efb10b44cd9c58ebd …
> CASMCMS-8954: Make BOS more efficient when patching CFS components

- CHANGELOG.md
- src/bos/operators/filters/filters.py
- src/bos/operators/status.py
- src/bos/operators/utils/clients/cfs.py
This changes BOS v2 so that it uses CFS v3 instead of CFS v2. This involves changing the endpoint URIs, changing a couple of the field names, and adding support for pagination on the GET components requests.
I tested this on mug and verified that it works as expected (and verified in the debug logs that it was appropriately hitting the v3 endpoints). I also lowered the CFS page size option and verified that it caused BOS v2 to properly paginate.
Additionally, the pagination logic used here is essentially the same as what I implemented for a Python tool used in the `docs-csm` repo to query CFS v3, and that has been in the CSM builds for a while now.
By default, BOS v2 is broken on CSM 1.5+ systems with more than 1000 nodes. In CSM 1.5, CFS v3 was introduced. It added support for paging, to …
> CASMCMS-8953: Use CFS v3 instead of v2

- CHANGELOG.md
- src/bos/operators/utils/clients/bos/options.py
- src/bos/server/controllers/v2/options.py
Backport of https://github.com/Cray-HPE/bos/pull/298
Because this is just a change in the default, including this in CSM 1.5.1 will only benefit customers who directly fresh install that version (instead of upgrading to it). But surely some folks will, so we may as well allow them to take advantage of the better default.
> CASMCMS-8438: Reduced v2 default polling frequency, reconciled discrepancies in default v2 option values

- CHANGELOG.md
- src/bos/operators/power_operator_base.py
Remove a `break` statement from the base power operator that prevents component status from being updated on more than one failing node, in the situation where a single CAPMC operation reports failures for multiple specific nodes.
I am making this PR against the `wip-2.0.38` branch because I plan to bundle together a few PRs that will eventually merge into the `support/2.0` branch as `v2.0.38`
This does not need a backport for the CSM 1.5+ BOS versions, because the switch to PCS removed this problematic code.
For posterity, this is the commit which added the code with the `break` statement:
https://github.com/Cray-HPE/bos/commit/ff6a4f0bd5625ae5f4b62c131541e791313e48f9
> CASMCMS-8995: v2: Fix bug causing some CAPMC failures to be incompletely interpreted by BOS

- CHANGELOG.md
- src/bos/operators/power_operator_base.py
Instead of immediately resorting to "one at a time" retries in the case of a vague CAPMC error, instead subdivide the list of components into smaller chunks, and only retry individually as a last resort.
I tested this on wasp. First I did a regular test, just making sure that nothing broke for a normal v2 session on there. Then I added some code so that it would pretend it was acting on 2800 nodes, 2 of which were bad. I basically just had code in the base power operator that told it to act on this big list of nodes, and then code in the capmc client to generate my fake CAPMC responses. I confirmed that the modified algorithm behaved as intended. I also added assertions afterward to check that the bad nodes were marked as such, and none of the others were.
> CASMCMS-8996: Improve scalability of how BOS v2 handles vague CAPMC operation failures

- CHANGELOG.md
- src/bos/common/tenant_utils.py
- src/bos/common/utils.py
- src/bos/operators/base.py
- src/bos/operators/power_on.py
- src/bos/operators/session_setup.py
- src/bos/operators/utils/boot_image_metadata/s3_boot_image_metadata.py
- src/bos/operators/utils/clients/bos/base.py
- src/bos/operators/utils/clients/bos/options.py
- src/bos/operators/utils/clients/bss.py
- src/bos/operators/utils/clients/cfs.py
- src/bos/operators/utils/clients/hsm.py
- src/bos/operators/utils/clients/pcs.py
- src/bos/operators/utils/clients/s3.py
- src/bos/reporter/components/state.py
- src/bos/reporter/node_identity.py
- src/bos/reporter/status_reporter/__main__.py
- src/bos/server/controllers/v2/base.py
- src/bos/server/controllers/v2/boot_set.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/controllers/v2/healthz.py
- src/bos/server/controllers/v2/options.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
- src/bos/server/redis_db_utils.py
This PR mainly makes 3 types of changes:
1. Currently some JSON responses are logged in "pretty" format with a ton of whitespace added, which makes the logs much larger than necessary. This compacts the JSON data before logging it.
2. A lot of exceptions are logged only printing their text but not their type. In some cases the type is obvious, but in other cases it is not, and knowing it could provide a helpful clue.
3, In many places when the BOS API is returning an error response to the caller, it also logs something related to this. In some cases, it does not. I've added debug logging calls to those places where they are missing.
Additionally, I found a handful of places where exceptions should be raised from other exceptions, to provide additional traceability. This PR adds that. …
> CASMCMS-8997: v2 logging improvements

- CHANGELOG.md
- Dockerfile
I am working on adding the input enforcement for BOS for the various limits that are currently only listed as being recommended. Doing this will be much easier using OAS 3.1. So this PR moves `openapi-generator-cli` to v7.6.0 in order to support that.
> CASMCMS-9002: Bump openapi-generator-cli to v7.6.0

- CHANGELOG.md
- bos-reporter.spec.in
One of my recent code changes started making a call to `bos.common` from BOS reporter. Turns out we don't package up `bos.common` into the BOS reporter RPM. This PR corrects that (and also stops including the large superfluous `__pycache__` files inside the RPM).
This will be backported to CSM 1.5.2 and CSM 1.4.5 as well.
I verified on starlord that this modification results in the necessary `bos.common` module being included in the RPM.
> CASMTRIAGE-7019: BOS reporter RPM: Add bos.common dependency, remove __pycache__

- CHANGELOG.md
- src/bos/operators/utils/clients/s3.py
Even though using the S3 client is thread-safe, instantiating it is not. If multiple BOS server threads attempt to do this at the same time, they can run into problems. This has been observed multiple times now by Harold during his bringup tests at UKMet. SAT tries to create multiple BOS sessions, and one or two of them will fail to be created because of this bug.
The simplest and most bulletproof fix is just to put a lock around the client instantiation.
Once the client has been instantiated, then this no longer happens, which is why it is only during system bringup that this is reliably seen. I am able to reproduce it on any system just by restarting the BOS pods and then creating multiple sessions simultaneously.
With this fix in place, however, I am unable to recreate the problem.
CSM …
> CASMCMS-9015: Instantiate S3 client in a thread-safe manner

- CHANGELOG.md
- api/openapi.yaml.in
A couple of places in the BOS API spec incorrectly used the `format` keyword when they meant to use the `pattern` keyword. This meant that the specified patterns were not being interpreted or enforced. This corrects that.
> CASMCMS-9022: Fix incorrect uses of format keyword in API spec

- CHANGELOG.md
- Dockerfile
- api/openapi.yaml.in
This updates the BOS API spec to OAS version 3.1, and also modifies it so that the previously-recommended field limits are now enfrorced (in the spec).
Moving to OAS 3.1 allowed me to enforce the limits on the boot set names in the API spec. In OAS 3.0 there was no good way to do that. Making that change meant I had to make some other small required changes in order to be compliant with OAS 3.1 (`nullable` is no longer allowed, `example` is gone and `examples` always maps to a list, etc)
Still remaining after this PR:
1. Modify the server code to enforce the limits at input time.
2. Add migration code to scrub or modify non-compliant records
3. Add docs-csm PR to backup BOS data automatically before upgrading to CSM 1.6, so that any scrubbed data is not lost.
Note that this PR is targeted …
> CASMCMS-9003: Update API spec to OAS 3.1; modify it to enforce limits

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
- src/bos/server/utils.py
Note: This PR is against a feature branch, not develop. I'll make the final PR to develop once I've completed work on the feature. I wanted to allow PR reviews at a more granular level in the meantime, hence this PR.
Modifications (mostly in the server code) to ensure that API restrictions are enforced (for things that are not automatically enforced by the generated API server code)
API spec changes:
* Require boot sets to have some form of node/group/role list specified (since they are useless without that)
* Make `BootSetName` a write-only property in a boot set (none of the server code ever gets the boot set name from the field inside the boot set --it only ever uses the key in the boot sets map. In truth, I think doesn't make sense to have the name field present in the boot set at …
> CASMCMS-9004: Enforce API restrictions in server code

- CHANGELOG.md
- src/bos/server/controllers/v2/components.py
When executing the applystage operation, BOS needs to look up the session ID using the tenant. The code has been changed to do this.
* Resolves [CASMCMS-9039]
* Change will also be needed in `master`
* `drax`
I applystage'd to a node to see if it effectively can do it. It could. I didn't experience the error I ran into before.
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
Low, it's already broken.
> CASMCMS-9039: Fix applystage to work under multi-tenancy

- CHANGELOG.md
- src/bos/operators/filters/__init__.py
- src/bos/operators/utils/boot_image_metadata/factory.py
- src/bos/operators/utils/clients/hsm.py
- src/bos/operators/utils/rootfs/__init__.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
> Merging CASMCMS-9039 fix into master

- CHANGELOG.md
- src/bos/operators/base.py
- src/bos/operators/utils/__init__.py
CASMCMS-8752 added timeouts to the API requests made by the BOS operators, preventing hangs that had been observed. We are seeing similar hangs at UKMet, and I see that these changes were never backported to CSM 1.4. This PR just backports those changes.
I am making this PR against the other CSM 1.4 BOS development branch I have going.
I tested this on wasp and found no issues.
> CASMCMS-9051: Backport CASMCMS-8752 changes to CSM 1.4

- CHANGELOG.md
- src/bos/reporter/client.py
- src/bos/reporter/status_reporter/__main__.py
Remove redundant function definitions in BOS reporter -- use the `bos.common.util` functions instead.
> CASMCMS-9052: Add request timeouts to BOS reporter

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/operators/base.py
- src/bos/operators/discovery.py
- src/bos/operators/session_setup.py
- src/bos/operators/status.py
- src/bos/operators/utils/__init__.py
- src/bos/operators/utils/clients/bos/options.py
- src/bos/reporter/client.py
- src/bos/server/controllers/v2/options.py
The LANL Crossroads system was experiencing BOSv2 failures, and the root cause turned out to be that PCS was trying to perform database transactions that were too large. Ideally PCS itself should be fixed, but in the meantime, this PR to BOS avoids the issue.
This creates a new BOS v2 option -- `max_component_batch_size_option`. Generally speaking, this will limit the number of components that a BOS operator will work on at a single time. This isn't exactly true -- for example, the discovery operator builds up its entire list of new components, even if that list exceeds this limit. But then when making the API call to BOS to create the new components, they are done in groups that do not exceed this size.
Similarly, the session setup operator figures out all of the components to be …
> CASMTRIAGE-7147: Create max_component_batch_size option

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/operators/utils/clients/bos/options.py
- src/bos/server/controllers/v2/options.py
- src/bos/server/controllers/v2/sessions.py
This adds a new BOS v2 option (`session_limit_required`) at the request of UKMet. This option is disabled by default. If it is disabled, then BOS works exactly as it does currently.
If the option is enabled, then attempts to create a BOS v2 session without specifying a limit will fail. For cases when the user actually wants to create a session without a limit, they can specify a limit of `*`.
I tested this on mug, along with the corresponding CLI changes.
Backports:
* https://github.com/Cray-HPE/bos/pull/347
* https://github.com/Cray-HPE/bos/pull/348
Cray CLI PRs:
* https://github.com/Cray-HPE/craycli/pull/158
* https://github.com/Cray-HPE/craycli/pull/159
* https://github.com/Cray-HPE/craycli/pull/160
> CASMCMS-9067: Add session_limit_required option

- CHANGELOG.md
- src/bos/reporter/client.py
Backport of https://github.com/Cray-HPE/bos/pull/351 for CSM 1.4
The changes are smaller because in CSM 1.4 and CSM 1.5, BOS reporter doesn't call the requests function from the BOS server code, but instead defines its own.
Testing this on wasp currently.
> CASMCMS-9081: Added the authorization token back into the bos-reporter API requests

- CHANGELOG.md
- src/bos/common/utils.py
- src/bos/operators/base.py
- src/bos/operators/power_on.py
- src/bos/operators/utils/clients/ims.py
The Scalable Boot Provisioning Service (SBPS) provides root filesystems to nodes when they boot. The images containing these root filesystems need to be tagged in the Image Management Service with 'sbps-project: true' before SBPS projects them to the nodes. With this mod, BOS tags any rootfs it is booting a node with with this key/value tag to ensure that it is projected during booting. This relieves the admin from needing to manually tag the image. This is a quality of life mod.
* Resolves [CASMCMS-9078]
* Change will also be needed in `master`
_List the environments in …
> CASMCMS-9078: BOS tags SBPS images

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/server/controllers/v2/sessiontemplates.py
The models generated by the openapi-generator are not able to handle the complicated schema used to enforce the requirement that BOS boot sets contain at least one of three possible node fields. The result is that even valid session templates are failing when attempting to create them.
This PR does two things to fix this:
1. Returns the API spec to a simpler form, where the above requirement is only found in the description field, but not enforced in the schema itself.
2. Modify the BOS session template validation code to instead validate this requirement "manually"
I tested this on mug and verified that it allows me to create a legal session template, but gives me an error if I try to create one with none of the node fields specified:
```
ncn-m001:~ # cray bos v2 sessiontemplates create …
```
> CASMCMS-9116: Fix boot set schema validation bug preventing valid session templates from being created

- CHANGELOG.md
- src/bos/common/tenant_utils.py
This updates the TAPMS endpoint to the correct value for CSM 1.6. No backports needed, because CSM 1.5 used the current value.
I tested this on fanta to verify that it works.
Before this PR:
```
Starting main run, version: 1.24.0, tag: YZ6kQ
Starting sub-run, tag: YZ6kQ-bos
ERROR (run tag YZ6kQ-bos): GET https://api-gw-service-nmn.local/apis/bos/v2/components (tenant: vcluster-blue): expected status code 200, got 400
ERROR (run tag YZ6kQ-bos): CLI command on behalf of tenant 'vcluster-blue' (bos v2 components list --format json) failed with exit code 2
ERROR (run tag YZ6kQ-bos): CLI command on behalf of tenant 'vcluster-blue' (bos components list --format json) failed with exit code 2
Ended sub-run, tag: YZ6kQ-bos (duration: 33.103587971s)
Ended run, tag: YZ6kQ (duration: 33.128497402s) …
```
> CASMCMS-9125: Update TAPMS endpoint for CSM 1.6

- CHANGELOG.md
- kubernetes/cray-bos/templates/post-upgrade-job.yaml
- src/bos/server/migrations/__init__.py
- src/bos/server/migrations/__main__.py
- src/bos/server/migrations/db.py
- src/bos/server/migrations/sanitize.py
- src/bos/server/migrations/validate.py
- src/bos/server/redis_db_utils.py
- src/bos/server/schema.py
New in CSM 1.6, BOS now enforces several things in the API spec that previously were unenforced. Notably, some names for session templates were previously allowed, but now are illegal. As things stand, these templates are essentially inaccessible via the API or CLI in CSM 1.6, because BOS will reject the requests due to the schema violation.
This PR changes what happens during the migration to a new BOS version to avoid that. Specifically, for all fields that are used in the API and CLI to reference BOS resources (their id/name field and, in some cases, the tenant field), it checks if they are legal. For components and sessions, if the fields are illegal, the associated resource is deleted, and a message is logged. I do not think this is likely to happen, because BOS had been validating …
> CASMCMS-9026: Sanitize BOS data during migration

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/operators/utils/clients/bos/options.py
- src/bos/server/controllers/v2/boot_set.py
- src/bos/server/controllers/v2/options.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
https://jira-pro.it.hpe.com:8443/browse/CASMCMS-7687
This adds a new BOS option -- `reject_nids` (based on customer request). By default, this option is disabled, and BOS works no differently than before. If the option is enabled, then:
1. When creating or validating a session template, report a fatal error if any of the boot sets contain node lists with a member that looks like a NID.
2. When creating a session, if the specified template runs afoul of the above, then fail.
3. When creating a session, if it specifies a limit that appears to contain a NID, then fail.
Note that when it comes to sessions, that check is only performed at the time the session is created -- not when the session setup operator runs, or a previously-staged session is applied.
Cray CLI PR: …
> CASMCMS-7687: Add reject_nids BOS option, to reject Sessions and Session Template which appear to reference NIDs

- CHANGELOG.md
- src/bos/server/controllers/v2/boot_set.py
When BOS is validating a session template, it includes a validation of all of its boot sets.
Currently, if the first boot set contains no fatal errors but does contain a warning, then this warning is returned immediately, skipping any check of the remaining boot sets (if any). Thus, if one of those remaining boot sets has a fatal error, it will be overlooked.
This PR changes the validation code so that it will only return a warning after checking all of the boot sets for more severe errors.
This bug probably has not been reported to us because most of our templates have a single boot set (and hopefully warnings are uncommon anyway). But with ARM support, probably more session templates will have multiple boot sets, increasing the likelihood of a customer seeing this. And regardless of …
> CASMCMS-9143: When validating boot sets, check all boot sets for severe errors before returning only warnings

- CHANGELOG.md
- src/bos/operators/utils/boot_image_metadata/__init__.py
- src/bos/operators/utils/boot_image_metadata/s3_boot_image_metadata.py
- src/bos/operators/utils/clients/ims.py
- src/bos/server/controllers/v2/boot_set.py
[CASMCMS-8425](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8425)
This modifies the boot set validation functions so that they look up the boot image in IMS and check that the boot set `arch` corresponds to the IMS boot image architecture. If they mismatch, this fails the validation. For other errors (e.g. image not in IMS, IMS not reachable), only a warning is issued. Based on discussions with Jason, I have opened two follow-on tickets to add options to modify that behavior: [CASMCMS-9145](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9145) (add option to make it fatal if IMS is unreachable) and [CASMCMS-9146](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9146) (add option to make it fatal if a boot image is not in IMS).
If the boot set has an `arch` of `Other`, then the …
> CASMCMS-8425: Include arch in boot set validation

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/common/options.py
- src/bos/operators/utils/boot_image_metadata/s3_boot_image_metadata.py
- src/bos/operators/utils/clients/ims.py
- src/bos/server/controllers/v2/boot_set.py
This adds a new BOS v2 option -- `arch_check_requires_ims`. It governs what happens when BOS needs to get image arch data from IMS, and there is an error getting it (other than the image not being in IMS). Currently, in that situation, an error is logged, but the architecture validation is skipped. If this new option is false (as it will be by default), then the current behavior will continue.
If this new option is true, then IMS errors will be considered fatal. If a boot set is being validated and one of these errors comes up, then the boot set validation will fail.
I tested this on mug, verifying that I got the correct behavior for both settings of the option, with IMS both up and down.
> CASMCMS-9145: Create BOS option arch_check_requires_ims

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/common/options.py
- src/bos/operators/utils/clients/cfs.py
Add an option 'cfs_read_timeout' to specify the amount of time in seconds to wait for a response from CFS before timing out.
* Resolves [CASMCMS-9162]
* Change will also be needed in `craycli`
* Documentation changes required in [CASMCMS-9162]
* `Odin`
I used a debug version where I could crank the minimum read timeout value down to 1 second. I did that and reproduced the errors seen in CAST-37016 which was the impetus driving CASMCMS-9162. When I increased the value back to 10, I did not see the errors. This was on a system where I had hand-crafted fake CFS components to the total of 3574 components to try and …
> CASMCMS-9162: Add 'cfs_read_timeout' option

- CHANGELOG.md
- src/bos/operators/session_setup.py
As far as I can tell, per-bootset CFS options have been broken in every official release from BOS 2.0.0 onward. This commit broke it:
https://github.com/Cray-HPE/bos/commit/c9dd021e789a96d0ef4050de863ba6af08106dcd
That commit fixed one bug (the `boot_set` argument was incorrectly being used as the name of the boot set, when in fact it was the boot set dict). However, it introduced another problem because it removed the `cfs` field access from the query. So after that commit, the code just looked in the boot set for a `configuration` field, which never exists, since that is not a valid field for a boot set. So it then always defaults to using the overall CFS value for the session template.
Fortunately, the fix is easy.
Shout out to `mypy` -- it found this error in a development branch I'm …
> CASMCMS-9165: Fix per-bootset CFS setting

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/operators/utils/clients/bos/options.py
- src/bos/operators/utils/clients/cfs.py
- src/bos/server/controllers/v2/options.py
Add cfs_read_timeout option
* Resolves [issue CASM-9162](issue link)
Once it builds, I'll test it a CSM-1.5 system.
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in …
> CASMCMS-9162: Add cfs_read_timeout option

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/server/controllers/v2/components.py
- src/bos/server/redis_db_utils.py
> [CASMCMS-9225](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9225) as a whole involves changes to a number of different files in BOS. In order to aid with review, I'm breaking the overall thing up into smaller PRs. Each will be built on top of each other, and will be merging into the `casmcms-9225-full` branch. Only once each sub-PR has been approved and merged will I merge that branch into develop.
[CASMCMS-9225](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9225) overall is addressing problems I found when investigating possible resource leaks in BOS (related to Josh Williamson's memory leak investigation with PCS). In the past we've made other changes to BOS to ensure that its requests to services like PCS and CFS do not get excessively large (this was done mostly by adding the …
> CASMCMS-9225: Added basic paging ability for GET requests to list components

- CHANGELOG.md
- src/bos/server/migrations/sanitize.py
The BOS migration code has a bug when it comes to renaming session templates. Specifically, it stores the renamed template using a database key based on the old template name. This results in the template being inaccessible using its new name. The fix is very tiny and straightforward.
> CASMCMS-9234: When renaming session templates during migration, use correct database key

- CHANGELOG.md
- src/bos/server/controllers/v2/components.py
- src/bos/server/redis_db_utils.py
The bulk of the changes for [CASMCMS-9225](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9225) are targeted for CSM 1.7.
For now, the only piece I plan to backport is some performance improvements when getting lists of BOS components. On large scale systems, the changes here improved performance by 3-4x.
This is a partial backport of https://github.com/Cray-HPE/bos/pull/396 for CSM 1.6
> CASMCMS-9225: Improve performance of large GET components requests

- src/bos/common/clients/endpoints/__init__.py
- src/bos/common/clients/endpoints/base_endpoint.py
- src/bos/common/clients/endpoints/base_generic_endpoint.py
- src/bos/common/clients/endpoints/base_raw_endpoint.py
- src/bos/common/clients/endpoints/defs.py
- src/bos/common/clients/endpoints/exceptions.py
- src/bos/common/clients/endpoints/request_error_handler.py
- src/bos/common/clients/endpoints/response_data.py
> [CASMCMS-9225](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9225) as a whole involves changes to a number of different files in BOS. In order to aid with review, I'm breaking the overall thing up into smaller PRs. Each will be built on top of each other, and will be merging into the [main PR](https://github.com/Cray-HPE/bos/pull/408) branch. Only once each sub-PR has been approved and merged will I merge that branch into develop.
>Full list of sub-PRs:
>1. [Added basic paging ability for GET requests to list components](https://github.com/Cray-HPE/bos/pull/396)
> 2. [Create generic endpoint classes](https://github.com/Cray-HPE/bos/pull/397)
> 3. [Create generic API client class](https://github.com/Cray-HPE/bos/pull/398)
> 4. [Create ApiClients class and provide it to BOS operators …
> CASMCMS-9225: Create generic endpoint classes

- CHANGELOG.md
- src/bos/server/redis_db_utils.py
I made a mistake in the backports for CSM 1.4 and CSM 1.5 yesterday. I didn't modify the code to account for the fact that `itertools.batched` is not available in the Python version BOS uses in those releases.
We already handle this same thing in `src/bos/operators/base.py`, where we use that function in CSM 1.6, but use an alternative for previous CSM releases. This PR makes the same adjustment to the redis DB utility code which uses `batched` in CSM 1.6.
I tested this on `baldar` and verified that it fixes the issue, passes basic BOS tests, and shows no signs of other issues.
> CASMCMS-9225: Do not use itertools.batched

- CHANGELOG.md
- src/bos/server/migrations/__main__.py
- src/bos/server/migrations/db.py
- src/bos/server/redis_db_utils.py
During CSM upgrades, the first run of the BOS migration job often fails, because the BOS databases are not yet ready. The job ultimately succeeds on retry, but it leaves some failed migration pods with ugly logs in its wake. This doesn't cause any problems except for possibly concerning an administrator who notices them.
This PR modifies the BOS migration job so that it waits for the databases to be ready before proceeding. It will retry for up to two minutes before failing. Based on what I have seen, this should allow it to succeed on its first attempt in most cases, preventing the problem described above.
I tested this on mug:
```
INFO:bos.server.migration:Beginning post-upgrade BOS data migration
WARNING:bos.server.redis_db_utils:Failed to query database session_templates : …
```
> CASMCMS-9177: Have BOS migration job wait for databases to be ready

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/common/options.py
- src/bos/operators/utils/clients/bss.py
- src/bos/operators/utils/clients/hsm.py
- src/bos/operators/utils/clients/ims.py
- src/bos/operators/utils/clients/pcs.py
- src/bos/server/controllers/v2/boot_set/ims.py
[Just like we did for CFS](https://github.com/Cray-HPE/bos/pull/382) with `cfs_read_timeout`, add BOS options to make the read timeouts configurable when making requests to BSS, IMS, HSM, and PCS.
I have tested this on mug.
This PR is for CSM 1.6.1. I will be backing "back" ports to `develop` (for CSM 1.7), `release/2.10` (for CSM 1.5), and `support/2.0` (for CSM 1.4).
There will also be corresponding PRs to `craycli` and `docs-csm` for these releases.
> CASMCMS-9242: Add BOS options: bss_read_timeout, ims_read_timeout, hsm_read_timeout, pcs_read_timeout

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/operators/utils/clients/bos/options.py
- src/bos/operators/utils/clients/bss.py
- src/bos/operators/utils/clients/hsm.py
- src/bos/operators/utils/clients/pcs.py
- src/bos/server/controllers/v2/options.py
CSM 1.5 backport of https://github.com/Cray-HPE/bos/pull/418
Note that it does not include `ims_read_timeout`, as BOS had no IMS client in CSM 1.5.
> CASMCMS-9242: Add BOS options: bss_read_timeout, hsm_read_timeout, pcs_read_timeout

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/operators/utils/clients/bos/options.py
- src/bos/operators/utils/clients/bss.py
- src/bos/operators/utils/clients/capmc.py
- src/bos/operators/utils/clients/hsm.py
- src/bos/server/controllers/v2/options.py
CSM 1.4 backport of https://github.com/Cray-HPE/bos/pull/418
Note:
* There is no `ims_read_timeout`, since BOS had not query IMS in CSM 1.4
* Instead of `pcs_read_timeout`, it has `capmc_read_timeout`, since BOS used CAPMC in CSM 1.4
> CASMCMS-9242: Add BOS options: bss_read_timeout, hsm_read_timeout, capmc_read_timeout

- src/bos/operators/base.py
> [CASMCMS-9237](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9237) as a whole involves changes to a number of different files in BOS. In order to aid with review, I'm breaking the overall thing up into smaller PRs. Each will be built on top of each other, and will be merging into the [main PR](https://github.com/Cray-HPE/bos/pull/408) branch. Only once each sub-PR has been approved and merged will I merge that branch into develop.
>Full list of sub-PRs:
>1. [Added basic paging ability for GET requests to list components](https://github.com/Cray-HPE/bos/pull/396)
> 2. [Create generic endpoint classes](https://github.com/Cray-HPE/bos/pull/397)
> 3. [Create generic API client class](https://github.com/Cray-HPE/bos/pull/398)
> 4. [Create ApiClients class and provide it to BOS operators …
> CASMCMS-9237: Create ApiClients class and provide it to BOS operators inside a context manager

- CHANGELOG.md
- src/bos/common/clients/endpoints/request_error_handler.py
- src/bos/common/tenant_utils.py
- src/bos/common/utils.py
- src/bos/operators/base.py
- src/bos/operators/power_off_forceful.py
- src/bos/operators/power_on.py
- src/bos/operators/session_cleanup.py
- src/bos/operators/session_setup.py
- src/bos/operators/status.py
- src/bos/server/controllers/v2/components.py
> [CASMCMS-9237](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9237) as a whole involves changes to a number of different files in BOS. In order to aid with review, I'm breaking the overall thing up into smaller PRs. Each will be built on top of each other, and will be merging into the [main PR](https://github.com/Cray-HPE/bos/pull/408) branch. Only once each sub-PR has been approved and merged will I merge that branch into develop.
>Full list of sub-PRs:
>1. [Added basic paging ability for GET requests to list components](https://github.com/Cray-HPE/bos/pull/396)
> 2. [Create generic endpoint classes](https://github.com/Cray-HPE/bos/pull/397)
> 3. [Create generic API client class](https://github.com/Cray-HPE/bos/pull/398)
> 4. [Create ApiClients class and provide it to BOS operators …
> CASMCMS-9237: CHANGELOG update, linting, update utils

- CHANGELOG.md
- kubernetes/cray-bos/templates/api-autoscaler.yaml
This is necessary because of the updated Kubernetes version for CSM 1.7.
> CASMCMS-9149: Update autoscaling apiVersion to support updated Kubernetes in CSM 1.7

- CHANGELOG.md
- src/bos/common/utils.py
- src/bos/operators/power_on.py
This PR addresses two problems and makes some small improvements.
Fixes:
1. In CASMCMS-9255, it was observed that the BOS code assumes that the kernel path will always end with `kernel`, which is not necessarily true. This PR replaces the current functions used for this to instead just parse the path as an `S3Url`, and then uses the existing `get_ims_id_from_s3_url` function to extract the IMS ID.
2. The current code assigns `components_list` to the `image_id_to_nodes` dict, using the `image_id` key. However, if two different sets of artifacts both reference the same IMS image, then each successive assignment will overwrite the previous one. This only ends up mattering in the case that the image tagging fails. In that case, it uses the component list to know which components need their …
> CASMCMS-9255: Improve kernel path parsing; fix bug logging image tagging errors

- CHANGELOG.md
- src/bos/server/controllers/v2/sessiontemplates.py
If you attempt to validate a nonexistent session template, it produces an internal server error:
```
Usage: cray bos v2 sessiontemplatesvalid describe [OPTIONS]
                                                  SESSION_TEMPLATE_ID
Try 'cray bos v2 sessiontemplatesvalid describe -h' for help.
Error: Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. 
```
This is because the endpoint does not properly handle the response from the `get_v2_sessiontemplate` method. This bug appears to exist in all released versions of BOS since this endpoint was introduced.
I discovered this as part of the type annotation work I am doing with CASMCMS-9264.
The fix is simple -- the …
> CASMCMS-9270: Properly handle being asked to validate nonexistent session template

- CHANGELOG.md
- Jenkinsfile.github
The BOS builds currently succeed, but github considers them to have failed because the image has the following vulnerability:
https://snyk.io/vuln/SNYK-PYTHON-WERKZEUG-6808933
Ordinarily, we would modify BOS so that it was no longer subject to this vulnerability. However, in this case, there is no easy way to accomplish this. Updating the werkzeug module requires several other modules to be updated, and those conflict with other parts of BOS. In order to resolve this CVE, we would have to make some fundamental changes to the way the BOS service is generated.
In addition, while this CVE is considered high severity, the path for vulnerability requires that the debugger be enabled, and that is never the case for us in production.
Finally, given that fewer and fewer resources are being …
> CASMCMS-9274: Prevent SNYK-PYTHON-WERKZEUG-6808933 from failing builds

- CHANGELOG.md
- src/bos/common/clients/endpoints/base_generic_endpoint.py
- src/bos/common/clients/endpoints/request_error_handler.py
- src/bos/common/clients/ims/images.py
- src/bos/common/clients/pcs/base.py
- src/bos/common/utils.py
This addresses a small number of the complaints `mypy` has. Only one of them has any functional impact on BOS itself. Previously the `duration_to_timedelta` function assumed that the timestamp being passed in would necessarily match the regular expression, so it did not check the result of its call to the `search` function. `mypy` does not approve. It sees, and it judges. The way that function worked before, if we did end up in a case where the regex didn't match, then I think it would have ended up raising either an `AttributeError` (when the code tried to call the `groups()` attribute of the `None` object). Now I have it explicitly check to see if it was a match or not. If not, then it will raise a brand new exception type just for this purpose.
That said, I don't know if I've ever seen …
> CASMCMS-9284: Correct some type annotation errors identified by mypy

- CHANGELOG.md
- src/bos/common/clients/endpoints/base_endpoint.py
- src/bos/common/clients/hsm/base.py
- src/bos/common/options.py
- src/bos/common/tenant_utils.py
- src/bos/common/types/__init__.py
- src/bos/common/types/components.py
- src/bos/common/types/general.py
- src/bos/common/types/sessions.py
- src/bos/common/types/templates.py
- src/bos/common/utils.py
- src/bos/common/values.py
- src/bos/operators/base.py
- src/bos/operators/discovery.py
- src/bos/operators/power_on.py
- src/bos/operators/session_setup.py
- src/bos/operators/status.py
- src/bos/server/controllers/v2/boot_set/artifacts.py
- src/bos/server/controllers/v2/boot_set/ims.py
- src/bos/server/controllers/v2/boot_set/sanitize.py
- src/bos/server/controllers/v2/boot_set/validate.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/controllers/v2/options.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
- src/bos/server/dbs/boot_artifacts.py
- src/bos/server/migrations/sanitize.py
- src/bos/server/migrations/validate.py
- src/bos/server/redis_db_utils.py
- src/bos/server/utils.py
The biggest content of this PR is creating the `bos.common.types` submodule, and beginning to define types to use for different BOS data structures. This PR only begins using a small number of these -- future PRs will continue that. This PR does touch a lot of files, mostly because it has to update the import paths for any files importing `JsonDict` or `JsonData`.
This PR has no functional impacts -- it's purely type checking enablement.
> CASMCMS-9285: Type annotation improvements

- CHANGELOG.md
- src/bos/operators/base.py
- src/bos/operators/filters/base.py
- src/bos/operators/filters/filters.py
- src/bos/operators/power_on.py
- src/bos/operators/session_setup.py
- src/bos/operators/status.py
- src/bos/server/controllers/v2/boot_set/ims.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/controllers/v2/options.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
- src/bos/server/migrations/sanitize.py
- src/bos/server/redis_db_utils.py
Just addressing some `pylint` complaints I just noticed. Most of this has no real impact. In one case (in the power on operator) I did refactor a function so that some of its code is moved into a separate function. The overall logic is unchanged (except I did change some log messages from errors to warnings, for cases where there was a transient failure but we are retrying -- I reserved the error log level for if we give up retrying)..
I am making this PR against my branch for another PR, only because I am editing a couple of the same files.
> CASMCMS-9287: Address some non-fatal pylint code complaints

- CHANGELOG.md
- src/bos/operators/session_completion.py
- src/bos/operators/session_setup.py
Normally, sessions are marked complete only by the session completion operator. However, in rare cases, the session setup operator does this, when the session cannot even start due to errors. In this case, the session setup operator instantiates a session completion operator of its own, and makes a call to one of its methods. The problem is, this instantiation of the completion operator does not have its API clients initialized (this is normally done as part of the `run` method), and leads to an exception.
This only is a problem because of the API client overhaul I did as part of [CASMCMS-9237](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9237), adding the context managers around the API clients, and having them setup and torn down by the run method.
The fix is easy. This PR moves the …
> CASMCMS-9288: Fix session setup operator attempting to use uninitialized API client

- CHANGELOG.md
- src/bos/operators/power_on.py
After the API client overhaul, I overlooked removing a now-unnecessary call to `raise_for_status` inside the power on operator. The exception in question will already have been raised from the API client error handler. This PR removes the now-unneeded call, and expands the `except` statement to catch all of the exceptions being raised from inside the API client.
The power on operator still expects the client to return a request response object, but it actually directly returns the desired token. This PR updates the operator to reflect that.
I tested this on wasp (where I found the problems) and verified that it resolved them.
This requires no backports -- it exists only in CSM 1.7, as it was introduced by [CASMCMS-9237](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9237).
> CASMCMS-9290: Remove no-longer-necessary call to raise_for_status in BOS power on operator

- CHANGELOG.md
- src/bos/common/clients/hsm/base.py
- src/bos/operators/power_on.py
After fixing [CASMTRIAGE-7853](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7853) and [CASMCMS-9288](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9288), the barebones boot test succeeds on wasp. But @spillerc-hpe astutely observed that the corresponding BOS session is marked successful despite not doing anything to the node.
I noticed this in the session setup logs:
```
2025-02-19T18:26:23.638755778Z 2025-02-19 18:26:23,638 - ERROR   - bos.common.clients.endpoints.request_error_handler - Non-2XX response (404) to POST http://cray-smd/hsm/v2//State/Components/Query; Not Found {"type":"about:blank","title":"Not Found","detail":"no such xname.","status":404}
```
Note the two consecutive forward slashes in the URL. Those are an error. The request works fine if they are changed to a …
> CASMCMS-9289: Remove extra / from HSM URLs to prevent request failures

- CHANGELOG.md
- src/bos/common/clients/api_client.py
- src/bos/common/clients/api_client_with_timeout_option.py
- src/bos/common/clients/bos/client.py
- src/bos/common/clients/bss/client.py
- src/bos/common/clients/cfs/client.py
- src/bos/common/clients/endpoints/base_generic_endpoint.py
- src/bos/common/clients/hsm/client.py
- src/bos/common/clients/ims/client.py
- src/bos/common/clients/ims/images.py
- src/bos/common/clients/pcs/base.py
- src/bos/common/clients/pcs/client.py
- src/bos/operators/base.py
- src/bos/operators/filters/filters.py
The underlying logic remains the same, but this changes the implementation to make it easier to placate `mypy`
> CASMCMS-9286: Reworked some of the API client implementation to resolve intractable mypy complaints

- CHANGELOG.md
- kubernetes/cray-bos/templates/db.yaml
CASMSEC-433: cray-bos-db container is now run with "nobody" user. As per kyverno cluster policy requirements, pod/container should not be run as root.
Yes
[CASMCMS-7866](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-7866)
* Merge with/before/after `<insert …
> CASMSEC-433: cray-bos-db container is now run with "nobody" user

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/common/clients/bos/options.py
- src/bos/common/options.py
- src/bos/common/types/components.py
- src/bos/common/types/options.py
- src/bos/common/types/session_extended_status.py
- src/bos/common/types/sessions.py
- src/bos/common/types/templates.py
This PR contains no functional changes to BOS. It does two things:
1. Updates the API spec to define the format of the `error_summary` field in the BOS extended session status. This format is fixed, so we may as well specify it in the API spec.
2. Creates additional helper classes and functions under bos.common.types. Most of these are not yet used. Many of these are just defining `TypedDict` versions of objects from the API spec. 
This is enablement for the next PR, which is going to address type annotation issues in the redis DB module.
> CASMCMS-9291: Add missing info to API spec; create more type annotation helpers

- CHANGELOG.md
- src/bos/server/controllers/v2/options.py
I noticed that the BOS logs now contain messages like this:
```
DEBUG:bos.server.controllers.v2.options:Logging level changed from INFO to 10
```
Where they previously looked like this:
```
DEBUG:bos.server.controllers.v2.options:Logging level changed from INFO to DEBUG
```
This impacts both CSM 1.6 and CSM 1.7, but not earlier. I figured out the change that caused it, and this reverts it back to the way it was. I have tested this on wasp and confirmed that it works.
CSM 1.6 backport:
https://github.com/Cray-HPE/bos/pull/464
> CASMCMS-9330: Print new logging level as string rather than integer

- CHANGELOG.md
- src/bos/common/clients/bos/base.py
- src/bos/server/controllers/v2/boot_set/sanitize.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/controllers/v2/options.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
- src/bos/server/dbs/boot_artifacts.py
- src/bos/server/migrations/db.py
- src/bos/server/migrations/sanitize.py
- src/bos/server/redis_db_utils/__init__.py
- src/bos/server/redis_db_utils/boot_artifacts_dbwrapper.py
- src/bos/server/redis_db_utils/component_dbwrapper.py
- src/bos/server/redis_db_utils/dbwrapper.py
- src/bos/server/redis_db_utils/defs.py
- src/bos/server/redis_db_utils/options_dbwrapper.py
- src/bos/server/redis_db_utils/redis_error_handler.py
- src/bos/server/redis_db_utils/session_dbwrapper.py
- src/bos/server/redis_db_utils/session_status_dbwrapper.py
- src/bos/server/redis_db_utils/session_template_dbwrapper.py
- src/bos/server/redis_db_utils/tenant_aware_dbwrapper.py
Break the `redis_db_utils` file into a module.
Split the DB wrapper class into a base class, with subclasses for each BOS database (along with an intermediate 'tenant-aware' DB for those BOS databases whose keys include the tenant).
Update the BOS code which uses the databases to reflect these changes.
> CASMCMS-9294: Improve Python type annotations, focused on DB modules

- CHANGELOG.md
- src/bos/operators/utils/boot_image_metadata/__init__.py
- src/bos/operators/utils/boot_image_metadata/factory.py
- src/bos/operators/utils/boot_image_metadata/s3_boot_image_metadata.py
The only functional change is that an exception is now raised if a boot set is missing the required `path` field. I think with the checks we have in other places, we should never hit that part of this code anyway, but if we do, we should fail on it.
The rest of this is purely improving the type annotations.
> CASMCMS-9295: Improve Python type annotations in boot_image_metadata 

- CHANGELOG.md
- src/bos/operators/session_setup.py
- src/bos/operators/utils/rootfs/__init__.py
- src/bos/operators/utils/rootfs/cpss3_provider.py
- src/bos/operators/utils/rootfs/factory.py
- src/bos/operators/utils/rootfs/rootfs_provider.py
- src/bos/operators/utils/rootfs/rootfs_provider_with_artifact_info.py
- src/bos/operators/utils/rootfs/sbps_provider.py
Next up in the continuing type annotation saga, the rootfs modules. The only thing to note here is that I did away with the `ProviderFactory` class. Its logic was slick, and gave the advantage that to implement a new provider, the factory class did not need to be modified. But it was harder to follow its logic, and made it harder for tools like mypy to figure out what it would be returning. I replaced it with a function that does hard-code the (two) different supported rootfs providers. It adds minimal overhead when adding/removing supported rootfs providers, and makes the logic much more obvious (to both humans and mypy).
> CASMCMS-9296: Improve Python type annotations in rootfs modules

- CHANGELOG.md
- src/bos/server/controllers/v2/components.py
- src/bos/server/redis_db_utils/dbwrapper.py
- src/bos/server/redis_db_utils/tenant_aware_dbwrapper.py
For some operations, BOS does a series of reads/writes for numerous single database entries, instead of combining these into a single call. The biggest impact is when update component states. This PR adds two new methods to the database wrapper -- `mget` and `mput`, which use the `mget` and `mset` Redis calls. This PR modifies the components controller to use these in places where it previously was doing things one entry at a time.
The logic does not change outside of this consolidation.
> CASMCMS-9340: Improve efficiency by using Redis mget/mset

- CHANGELOG.md
- src/bos/server/controllers/v2/sessiontemplates.py
The `/sessiontemplatetemplate` endpoint was added because people wanted a way to get a skeleton template that they could edit in order to create their own session template. When creating a session template, the `name` is not specified as part of the request body -- it is specified as part of the path (or in the case of the CLI, it is specified using a separate argument). In either case, the user would need to manually delete that field from their request body, otherwise the create will fail. So it makes more sense not to include that field in the output. That's what this PR does.
Note that this change does not violate the API schema, because the `name` field is listed as read only, but not as required.
> CASMCMS-8666: Remove name field from /sessiontemplatetemplate response

- CHANGELOG.md
- src/bos/common/clients/s3.py
This adds code to BOS that mirrors what IMS does when processing manifest files -- if the file is bigger than 1M, it gives an error, rather than trying to use it. This avoids problems like OOM issues. This is only likely to occur if someone has made a mistake with their S3 artifacts, but fortunately the safeguard is very simple and does not involve any additional S3 calls, so the overhead is low.
I tested this on mug and verified that it properly rejected such manifests.
> CASMCMS-7902: Check size before loading image manifest to avoid errors

- CHANGELOG.md
- src/bos/common/utils.py
- src/bos/operators/base.py
- src/bos/server/__main__.py
- src/bos/server/controllers/v2/base.py
- src/bos/server/controllers/v2/boot_set/ims.py
- src/bos/server/controllers/v2/boot_set/sanitize.py
- src/bos/server/controllers/v2/boot_set/validate.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/controllers/v2/healthz.py
- src/bos/server/controllers/v2/options.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
- src/bos/server/options.py
This PR fixes two logging bugs in BOS.
The first one is minor, and is very similar to the bug fixed by [CASMCMS-9330](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9330). When the BOS operators detect a new logging level and change it, the log messages they write specify the new log level as an integer, not as a string. This PR corrects that.
The second issue is a bigger deal, but has actually been present in BOS for a long time. Specifically, the BOS server does not update its logging level dynamically. It thinks that it does -- it starts up a thread that periodically checks it and updates it. However, that thread is started by BOS in the main server startup code. The problem is, that code only starts up the thread in one of the BOS processes in any given pod. But BOS is multiprocess, …
> CASMCMS-9351: Fix logging bugs

- CHANGELOG.md
- src/bos/common/utils.py
Recently while working on other BOS tickets, I added some additional debug logging statements, and on mug I noticed that this resulted in some OOM errors for some operator pods. mug does have more nodes than we have ever tested in the field, and so it is unsurprising that some of the API responses it receives are larger than normal. But we use the `compact_response_text` function to reduce the size of this data when we log it. And interestingly, the OOM issues only happened when I added the calls to log the responses -- the responses were being handled fine otherwise. This caused me to look closer at compact_response_text, and I realized it was inefficient in two ways.
First, the primary cause of the OOM issues is that it is very memory inefficient. It starts by calling the `split` …
> CASMCMS-9357: Make compact_response_text more efficient

- CHANGELOG.md
- src/bos/common/clients/endpoints/base_generic_endpoint.py
- src/bos/operators/base.py
- src/bos/operators/filters/base.py
- src/bos/operators/power_on.py
- src/bos/operators/session_setup.py
- src/bos/server/controllers/v2/boot_set/ims.py
- src/bos/server/redis_db_utils/redis_error_handler.py
When debugging [CASMTRIAGE-8072](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-8072) it was discovered that when the session setup operator received a 404, it did not log all of the relevant information included with the exception (in this case, the item which was not found). This made debugging more challenging. See that ticket for full context.
That ticket was found on CSM 1.5, and some parts of that problem have already been addressed in CSM 1.7. This PR makes a few tweaks to the BOS server and operator logging to help capture problems when debugging. I have tested it on mug.
> CASMCMS-9353: Improve exception logging

- CHANGELOG.md
- src/bos/common/types/components.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/dbs/boot_artifacts.py
- src/bos/server/redis_db_utils/boot_artifacts_dbwrapper.py
- src/bos/server/redis_db_utils/dbwrapper.py
- src/bos/server/redis_db_utils/defs.py
Modify the V2 controller code for components endpoints to make better use of type annotations.
Also minor refactoring and linting of same.
As part of this, I slightly adjusted the boot artifacts `TypedDict`s, to stop distinguishing between those with and without timestamp fields. Because of how `mypy` handles `TypedDict`s, you can't just have one inherit from another, making an optional parent class field to be required in the child class (which is what ideally we should do with boot artifacts and the timestamp field). See https://github.com/python/mypy/issues/7435
> CASMCMS-9346: Improve type annotations for BOS components controller

- CHANGELOG.md
- src/bos/server/controllers/utils.py
- src/bos/server/controllers/v2/components.py
The fix for [CASMCMS-9355](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9355) is going to require some changes to the procedure used for bulk component updates. Trying to do that the way the functions currently work is going to result in a mess. This PR refactors the bulk component patch functions. It doesn't change the current behavior (beyond perhaps the exact wording of some log and error messages), but it will make the changes needed for CASMCMS-9355 much easier and cleaner.
Basically, this PR moves the actual patching itself into the main bulk patch function. The two main child functions are now responsible for providing the parent function with the current component data, and the patch data for those components. Missing components are now signaled by a specific new exception …
> CASMCMS-9362: Refactor components bulk patch functions

- CHANGELOG.md
- src/bos/common/clients/bos/base.py
- src/bos/common/clients/bos/components.py
- src/bos/operators/session_setup.py
The `skip_bad_ids` parameter for bulk component patching is added with https://github.com/Cray-HPE/bos/pull/493.
With that in place, this PR modifies the session setup operator to make use of it.
Without this PR, if the session setup operator finds a session that includes invalid components, the attempt to patch the component fails, and it breaks the operator. See [CASMCMS-9355](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9355) for full details.
One might argue this should have been filtered out earlier, when the session was created, but unfortunately this is not possible. In the case where this bug was found, the issue was that the session template included an HSM group, and that group included invalid IDs. While it would be possible to validate that when the session is created (and …
> CASMCMS-9355: Update session setup operator to gracefully handle invalid components

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/common/clients/bos/base.py
- src/bos/common/clients/bos/components.py
- src/bos/operators/session_setup.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/redis_db_utils/dbwrapper.py
The problem being solved with [CASMCMS-9355](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9355) is that it is possible for the session setup operator to process a session and come up with a list of invalid component IDs that it should include. When it attempts to patch those components in BOS, the fact that some of them do not exist causes the patch request to fail, which breaks the session setup operator.
The simplest solution is to have BOS treat such components the same way it does for other cases (like the component being disabled in HSM) -- just to filter it out and not include it in the session. Doing this inside the operator itself is the natural thought, but it turns out to be easier to just make this part of the patch operation. Especially on larger scale systems, this will be …
> CASMCMS-9381: Add skip_bad_ids parameter to bulk components patch endopoint

- CHANGELOG.md
- src/bos/common/tenant_utils.py
`mypy` was reporting a bunch of errors inside the `get_tenant_component_set` function, because of uncertainty around the types that may be encountered in the response from TAPMS. This just adds explicit type annotations to reflect the format we expect the TAPMS response to have,
> CASMCMS-9383: tenant_utils: Resolve mypy complaints

- CHANGELOG.md
- src/bos/common/clients/hsm/base.py
- src/bos/common/clients/hsm/groups.py
- src/bos/common/clients/hsm/inventory.py
- src/bos/common/clients/hsm/partitions.py
- src/bos/common/clients/hsm/state_components.py
- src/bos/common/clients/hsm/types.py
- src/bos/common/clients/ims/utils.py
HSM client: This PR creates some `TypedDict`s to represent the data that is returned from HSM API calls, and adds some `cast` calls to tell `mypy` that this is what the responses are.
IMS client: Just changed how some regex pattern matching is done to be more precise. Instead of relying on an exception being raised when there is no match found, this explicitly verifies whether or not there was a match. This placates mypy.
> CASMCMS-9385: Resolve mypy complaints in HSM and IMS clients

- CHANGELOG.md
- src/bos/operators/utils/boot_image_metadata/factory.py
The fact that the `BootImageMetaDataFactory` return type was the `BootImageMetaData` superclass was causing `mypy` distress, because all of the calls were assuming that the type they got back was `S3BootImageMetaData`. This is because at the moment, that is the only type of boot image metadata that BOS supports. The code was written at a time when it was envisioned that BOS may eventually support multiple types of boot artifacts (I assume), but so far that has not come to pass.
Eventually it would make sense to just simplify this entirely and re-write this part of the code to just have the one type, and get rid of the whole factory idea. But for now, to get type checking working, we can just modify the factory type annotation to reflect the only type of object it can currently return. 
No …
> CASMCMS-9392: Resolve mypy concerns around BootImageMetaDataFactory

- CHANGELOG.md
- src/bos/server/controllers/v2/boot_set/validate.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
This PR resolves `mypy` complaints related to the sessions controller. Most of this just involves using `cast` to convey type information that `mypy` cannot automatically infer. This PR also moves a somewhat unwieldy conditional into its own helper function, mainly for readability of the code.
> CASMCMS-9395: Fix type annotations for sessions controller

- CHANGELOG.md
- src/bos/common/types/templates.py
- src/bos/server/controllers/v2/boot_set/validate.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
This cleans up some type annotations around the sessiontemplatetemplate endpoint, to resolve a complaint `mypy` was making. Specifically, it modifies the `SessionTemplate` `TypedDict` to match the API schema, and then it explicitly uses the relevant `TypedDict` structures when constructing the return data for this endpoint.
There is no functional change here -- just type annotation cleanup.
> CASMCMS-9393: Fix type annotations for sessiontemplatetemplate endpoint

- CHANGELOG.md
- src/bos/common/types/templates.py
- src/bos/server/controllers/v2/boot_set/validate.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
- src/bos/server/migrations/sanitize.py
- src/bos/server/migrations/validate.py
The BOS server migration code (which runs when BOS is updated) had some errors, which this PR cleans up. Most of them were purely type annotation errors. For example, when the migration code was annotated, the DB keys were all typed as either strings or bytes. But when we did the database rework, we ended up ensuring that they would always be strings by the time the migration code was looking at them. There was also a case where a function was annotated as returning a string in the case of an error, but it really just raised an exception in that case, and always returned None.
mypy also did identify one bug in the migration code, albeit one which only impacted a log message. A call to `delete_template` mistakenly included the template data in a field intended for an error message (or …
> CASMCMS-9391: Clean up type annotations in BOS server migration code

- CHANGELOG.md
- src/bos/common/options.py
- src/bos/common/types/components.py
- src/bos/operators/actual_state_cleanup.py
- src/bos/operators/base.py
- src/bos/operators/configuration.py
- src/bos/operators/discovery.py
- src/bos/operators/power_off_forceful.py
- src/bos/operators/power_off_graceful.py
- src/bos/operators/power_on.py
- src/bos/operators/session_cleanup.py
- src/bos/operators/session_completion.py
- src/bos/operators/session_setup.py
- src/bos/operators/status.py
- src/bos/server/options.py
* Simplified the `_check_defaults` logic (in such a way that it also calms down poor `mypy`).
* Used `dict` `copy` method to copy a `dict` instead of calling `dict` with the old `dict` as the argument, as the latter confused `mypy`.
* Otherwise, just added in missing type annotations or necessary `cast` calls
This adds annotations to a bunch of operator methods and variables which lack them.
It also redefines the component event stats type, to handle how the operators store a class variable with a field name from that structure.
As always, some `cast`s were added to keep `mypy` happy.
This doesn't completely finish the type annotation work for the operators, but this PR had grown large enough that I thought it best to stop it here, and begin another one to continue that work.
> CASMCMS-9390/CASMCMS-9394: Fix type annotations

- CHANGELOG.md
- src/bos/common/clients/bss/boot_parameters.py
- src/bos/common/clients/pcs/power_status.py
- src/bos/common/clients/pcs/transitions.py
- src/bos/common/clients/pcs/types.py
- src/bos/operators/power_off_forceful.py
* Add type annotations to BSS and PCS clients
* Simplify transitions endpoint with use of `functools.partialmethod`
* Remove unused API parameters from power status query call
> CASMCMS-9403: BSS & PCS clients: Add type annotations

- CHANGELOG.md
- src/bos/operators/session_setup.py
This fixes the type annotation issues in the session setup operator.
Some just required the usual explicit annotation of variables, to let `mypy` know what is intended. But typing the code as-is was going to be complicated because of the fact that the same class was used for both staged and regular sessions. I realized that it was only a very small number of places where the behavior was actually different, so I moved the bulk of the existing code into an abstract base class, and then created two concrete child classes -- one for handling regular sessions, and one for handling staged sessions. This dramatically simplified the type annotation, and actually also simplified the code itself, since it removed the previous "if staged" conditionals that were peppered through the class. …
> CASMCMS-9407: Refactor session setup operator to resolve type annotation issues

- CHANGELOG.md
- src/bos/common/clients/s3/s3.py
There are 3 BOS methods which return objects that come from the `boto3`/`botocore` modules. Currently, the return types for these methods is not explicitly annotated, because this is not possible to do using usual methods. The types in question are classes which do not exist at the time that type checking is done. There are stubs modules that allow `mypy` to infer the types, but it will still complain about methods that are not explicitly annotated. We could just suppress those errors, but it's possible to do the explicit type annotation. It just requires some care be taken, to avoid using things that are not present when the code is actually run in production. This PR adds in the explicit type annotations, but uses a `TYPE_CHECKING` conditional to ensure that the extra stuff is only done …
> CASMCMS-9413: Add explicit annotations for S3 methods

- CHANGELOG.md
- src/bos/common/types/components.py
- src/bos/common/types/sessions.py
- src/bos/common/values.py
This just defines a few new types that I will be using in an upcoming PR to clean up the remaining type annotation issues relating to components and sessions. This PR itself just adds the definitions, but doesn't modify the other code to use them yet.
> CASMCMS-9414: Create helper types for sessions and component type annotation

- CHANGELOG.md
- src/bos/server/redis_db_utils/dbwrapper.py
It turns out that `mypy` has a little trouble with inferring type information in some cases when `partialmethod` is used, particularly in combination with `overload`. This PR refactors `dbwrapper` to avoid this problematic combination. The result has the same execution logic as before, but in a way that doesn't make `mypy` sad.
> CASMCMS-9415: Refactor dbwrapper to resolve type annotation issues

- CHANGELOG.md
- src/bos/common/clients/bos/base.py
- src/bos/common/clients/bos/components.py
- src/bos/common/clients/bos/session_templates.py
- src/bos/common/clients/bos/sessions.py
- src/bos/common/clients/endpoints/base_generic_endpoint.py
- src/bos/common/clients/endpoints/defs.py
- src/bos/common/clients/hsm/base.py
- src/bos/common/clients/hsm/groups.py
- src/bos/common/clients/hsm/inventory.py
- src/bos/common/clients/hsm/partitions.py
- src/bos/common/clients/hsm/state_components.py
- src/bos/operators/base.py
- src/bos/operators/filters/filters.py
This PR does a refactoring of the base generic API client, the BOS client, and the HSM client, to resolve the remaining mypy issues they had. It also fixes type issues in the filters code used by the operators.
The core logic is unchanged. The size of the PR is just a reflection of how many parts of BOS import this code, and needed their type annotations updated accordingly.
With this PR in place, the `mypy` check gives BOS a clean bill of health! The next PR will modify the Jenkinsfile to make the `mypy` check a gate to the builds, like we have with `pylint` currently.
I've also tested this code on mug and verified that it hasn't introduced some unforeseen bugs.
> CASMCMS-9418: Resolve type annotation issues in BOS client, HSM client, and filters

- CHANGELOG.md
- Jenkinsfile.github
As the description says, this PR just makes it so that if `mypy` fails, the build fails, to ensure that we don't add new code which is not type safe.
> CASMCMS-9412: Update Jenkinsfile to make failed mypy checks fail the build

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/common/types/templates.py
- src/bos/server/controllers/v2/sessiontemplates.py
Currently, the API spec uses the same schema definition for the body of session template PUT and PATCH requests. This schema has the boot set field as required, because new session templates are useless without it. However, when patching a template, it should not be required, since there are other fields that may be modified.
This PR updates the API spec to create a separate schema for session template patching, adds an associated datatype in the BOS typing library, and updates the relevant code to use it. The actual code is mostly unchanged, beyond using the new data type.
I have tested this on mug and verified that it now allows me to patch without having to include the boot sets.
> CASMCMS-9426: Allow session template patches to omit the boot_sets field

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/common/types/components.py
- src/bos/common/values.py
- src/bos/operators/actual_state_cleanup.py
- src/bos/operators/base.py
- src/bos/operators/configuration.py
- src/bos/operators/discovery.py
- src/bos/operators/power_off_forceful.py
- src/bos/operators/power_off_graceful.py
- src/bos/operators/power_on.py
- src/bos/operators/session_cleanup.py
- src/bos/operators/session_completion.py
- src/bos/operators/session_setup.py
- src/bos/operators/status.py
- src/bos/server/controllers/v2/sessions.py
BOS component fields `phase` and `action` both have a specific set of possible values, but the API spec currently just defines them as general string values. This means that someone could accidentally (or maliciously) do a component patch operation and set either of these fields to a value that BOS has no understanding of, and that we never test. There is no upside to this flexibility in the spec.
This PR modifies the API spec to define enumerations for each of these fields. It then modifies the server code accordingly, to ensure that those fields always contain those values.
I also did a refactoring of the operator classes, since they currently awkwardly use the `name` property to actually mean "new action field value", and also use it as a kind of boolean test for whether an operator …
> CASMCMS-9428: Change component phase and action fields to enumerations

- CHANGELOG.md
- src/bos/common/utils.py
- src/bos/server/controllers/v2/session_status.py
- src/bos/server/controllers/v2/sessions.py
The `_get_v2_session_status` function in the sessions controller has become unwieldy. I noticed this during my type-annotation work, but didn't address it at the time.
This PR moves the logic for that function into a new session_status module. I refactored it into a class structure, since that reduced the amount of data that needed to be passed between different functions when calculating the status.
This PR also creates a new `cached_property` helper class, which is just the regular `functools.cached_property` class, but modified to make the property read-only. I originally named it `cached_property_readonly`, which led me to discover and report [a `pylint` issue](https://github.com/pylint-dev/pylint/issues/10377). I actually have [a PR up to fix that …
> CASMCMS-9429: Refactor _get_v2_session_status logic into its own module

- CHANGELOG.md
- api/openapi.yaml.in
CPS/DVS are removed in CSM 1.7, replaced by SBPS. This PR updates the BOS API spec to change the CPS/DVS examples to instead use SBPS. This only modifies example values in the spec -- it has no impact on the service at runtime.
The values were taken from the example values used on [the SBPS setup page in docs-csm](https://github.com/Cray-HPE/docs-csm/blob/release/1.7/operations/boot_orchestration/Create_a_Session_Template_to_Boot_Compute_Nodes_with_SBPS.md)
> CASMCMS-9432: Update API spec examples to use SBPS instead of CPS/DVS

- CHANGELOG.md
- src/bos/server/controllers/v2/sessiontemplates.py
CPS/DVS are removed in CSM 1.7. The example session template returned by the `sessiontemplatetemplate` endpoint specifies CPS/DVS in its boot set. This PR updates the example data it returns so that it uses SBPS instead. The values were taken from the example values used on [the SBPS setup page in docs-csm](https://github.com/Cray-HPE/docs-csm/blob/release/1.7/operations/boot_orchestration/Create_a_Session_Template_to_Boot_Compute_Nodes_with_SBPS.md)
> CASMCMS-9433: Update sessiontemplatetemplate endpoint to use SBPS

- CHANGELOG.md
- src/bos/common/clients/hsm/client.py
- src/bos/common/clients/hsm/locks.py
- src/bos/common/clients/hsm/types.py
- src/bos/operators/filters/filters.py
- src/bos/operators/session_setup.py
Add code to remove nodes that are locked in HSM when creating a BOS session, to make it more obvious when this is done. I tested this on mug.
I also slightly changed the order in which nodes are filtered during session setup, to try to whittle down the list before making API calls that specify the node list (to try and keep such calls smaller).
> CASMCMS-8843: Remove locked HSM nodes when starting session

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/common/options.py
- src/bos/common/types/options.py
- src/bos/operators/status.py
This removes the `disable_components_on_completion` option from the code and from the spec file. It changes the single place in the code where it is used, so it follows the behavior it would have if the option was set to true (the default before).
I'll also have follow-on PRs to docs and craycli.
> CASMCMS-8131: Removed disable_components_on_completion option due to lack of use and lack of testing
