- api/openapi.yaml.in
- kubernetes/cray-bos/values.yaml.in
- src/bos/operators/utils/clients/bos/__init__.py
- src/bos/operators/utils/clients/bos/generic_http.py
- src/bos/operators/utils/clients/bos/session_templates.py
- src/bos/operators/utils/clients/bos/sessions.py
- src/server/bos/__main__.py
- src/server/bos/controllers/v1/healthz.py
- src/server/bos/controllers/v1/sessiontemplate.py
- src/server/bos/controllers/v2/healthz.py
- src/server/bos/controllers/v2/sessiontemplates.py
- src/server/bos/specialized_encoder.py
> Casmcms 7705

- README.md
(cherry picked from commit c8811fdaefceafa2be8ed2c2e59923b45960ad21)
Trivial change to force the BOS chart to rev.
> Improve README.md trivially

- Jenkinsfile.github
- Makefile
- bos-reporter.spec.in
CASMCMS-7794: Build BOS rpms for SLES15SP2 and SLES15SP3 distributions.
Build the BOS rpms for the SLES15SP2 and SLES15SP3 distributions.
The COS compute node images are SLES-based, so we need to build the
rpm with the distribution environment.
To prevent the accumulation of files from previous stages in the build,
clean up the contents of the RPM build directories after publishing its
contents. This does clean-up ahead of time, so that SLES15SP2 files are not
included with SLES15SP3 files.
Publish the Helm chart and Docker image ahead of the RPMs.
This helps speed up development because developers are less interested in
the RPM results.
* …
> Casmcms 7794

- api/openapi.yaml.in
- kubernetes/cray-bos/values.yaml.in
- src/bos/common/utils.py
- src/bos/operators/actual_state_cleanup.py
- src/bos/operators/filters/__init__.py
- src/bos/operators/filters/filters.py
- src/bos/operators/session_setup.py
- src/bos/operators/utils/clients/bos/options.py
- src/bos/reporter/status_reporter/__main__.py
- src/bos/server/controllers/v2/options.py
- src/bos/server/controllers/v2/sessions.py
Point in time merge of existing 7931 code into bos-v2 to facilitate shared, on-system debugging (mug).
* Contributes to CASMCMS-7931 in a do-no-harm capacity.
> Casmcms 7931

- src/bos/operators/actual_state_cleanup.py
- src/bos/operators/filters/filters.py
> Adjust filters to do an initial query from BOS

- src/bos/operators/filters/filters.py
> Re-instate init call to ActualStateAge.

- src/bos/operators/actual_state_cleanup.py
> Remove list structure around patch payload

- src/bos/server/controllers/v2/components.py
> Remove annotation.

- CHANGELOG.md
- Jenkinsfile.github
Adds SLES SP4 support
Also cleans up some whitespace issues
* Resolves CASMCMS-8058
* Lemondrop
- Installed rpms
None
> CASMCMS-8058: Add sles sp4 build

- CHANGELOG.md
- Jenkinsfile.github
Adds SLES SP4 support
* Resolves CASMCMS-8058
* Lemondrop
- Installed rpms
None
> Merge sles sp4 changes to the release branch

- CHANGELOG.md
- kubernetes/cray-bos/Chart.yaml.in
- kubernetes/cray-bos/values.yaml.in
- update_versions.conf
CASMCMS-8088
Pulling in changes to properly reference unstable branches rather than hard-coding to stable ones.
This pulls changes from develop.
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Were continuous …
> Casmcms 8088 release 2.0.0

- api/openapi.yaml.in
Fixes the description for stage
* Resolves CASMCMS-8079
* local
Tested cli generation
None
> CASMCMS-8079: Fix session creation description for stage

- CHANGELOG.md
- kubernetes/cray-bos/templates/db.yaml
- kubernetes/cray-bos/values.yaml.in
Added PVC override for cray bos chart
Yes
* Resolves [issue id](issue link) https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7862
Mug
Trialed a helm deployment 
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Were the install/upgrade-based validation checks/tests run (goss …
> overrides for PVC storage class

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/common/tenant_utils.py
- src/bos/common/utils.py
- src/bos/operators/session_completion.py
- src/bos/operators/session_setup.py
- src/bos/operators/utils/__init__.py
- src/bos/operators/utils/clients/__init__.py
- src/bos/operators/utils/clients/bos/base.py
- src/bos/operators/utils/clients/bos/options.py
- src/bos/operators/utils/clients/bos/session_templates.py
- src/bos/operators/utils/clients/bos/sessions.py
- src/bos/operators/utils/clients/bos/sessions_status.py
- src/bos/operators/utils/clients/bss.py
- src/bos/operators/utils/clients/cfs.py
- src/bos/operators/utils/clients/hsm.py
- src/bos/operators/utils/clients/pcs.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
- src/bos/server/v1_v2_migration.py
Adds tenant awareness for sessions and session templates
Adds component filtering based on tenant
Adds operator support for multi-tenancy
* Resolves CASMCMS-8433
* Resolves CASMCMS-8434
* Resolves CASMCMS-8454
* Mug
Tested all endpoints and session creation for cases with tenants, no tenants and invalid tenants.
None
> CASMCMS-8433/8434/8454: Update endpoints and operators for multi-tenancy

- CHANGELOG.md
- kubernetes/cray-bos/templates/clusterrolebinding.yaml
- kubernetes/cray-bos/templates/db.yaml
- kubernetes/cray-bos/templates/post-upgrade-job.yaml
- kubernetes/cray-bos/templates/role.yaml
- kubernetes/cray-bos/templates/rolebinding.yaml
- kubernetes/cray-bos/templates/serviceaccount.yaml
- src/bos/common/tenant_utils.py
- src/bos/server/controllers/v1/session.py
- src/bos/server/controllers/v1/sessiontemplate.py
- src/bos/server/controllers/v1/status.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
- src/bos/server/migrations.py
- src/bos/server/redis_db_utils.py
* Adds an error to the v1 endpoints when a tenant is specified
* Rejects v2 calls to create resources when the tenant is invalid
* Update database keys to prevent collisions and add migration to the new database key format.
* Resolves CASMCMS-8552
* Resolves CASMCMS-8562
* Resolves CASMCMS-8563
* Mug
- Deployed, verified database keys and the ability to retrieve new and old keys.  Tested v1 endpoints with and without tenants.  Tested v2 endpoints with valid and invalid and no tenant cases.
None
> BOS multi-tenancy updates for CASMCMS-8552/8562/8563

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/common/tenant_utils.py
- src/bos/server/controllers/v1/sessiontemplate.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/controllers/v2/sessions.py
Fixes several issues found during the crossroads scale testing (CASMCMS-8440)
* Resolves CASMCMS-8612
* Resolves CASMCMS-8613
* Resolves CASMCMS-8614
* Resolves CASMCMS-8617
* Resolves CASMCMS-8630
* Resolves CASMCMS-8645
* Ashton
Ran through the problem scenarios, or as close as I could get, and verified the output.  Because some of these were scale bugs I had to write scripts to mimic the scenarios and exploit the smaller window on the smaller machine.
None
> Bug fixes for BOS scale testing

- src/bos/common/tenant_utils.py
Updates the endpoint BOS uses for tapms to match the work done for CASMPET-6433
* Resolves CASMCMS-8665
* Ashton
Ran through calls for components, templates and sessions.
None
> CASMCMS-8665: Fixes the tapms endpoint

- CHANGELOG.md
- Jenkinsfile.github
Add support for sles-sp5
CASMCMS-8676
> CASMCMS-8676 - Support for sles-sp15

- CHANGELOG.md
- api/openapi.yaml.in
- constraints.txt
- requirements.txt
- src/bos/server/controllers/v1/sessiontemplate.py
This PR reverts all changes made to support/2.0 after 2.0.18 except for Ryan's bugfix for CASMCMS-8532
> Revert changes made after 2.0.18 except for Ryan's bugfix

- CHANGELOG.md
- kubernetes/cray-bos/values.yaml.in
Added etcd_disable_prestop for etcd chart
* Resolves CASMCMS-8684
* Mug
Deployed and tested basic api commands
None
> CASMCMS-8684: Added etcd_disable_prestop for etcd chart

- CHANGELOG.md
- src/bos/operators/base.py
##
Creates a small fix for attribute lookup in late added is_alive threadcheck.
> Fixup is_alive lookup

- CHANGELOG.md
- bos-reporter.spec.in
Updated the spire-agent path
* Resolves [CASMINST-6677
> CASMINST-6677: Update spire-agent path

- CHANGELOG.md
- api/openapi.yaml.in
> Correct 2 minor errors in API spec description fields

- CHANGELOG.md
- src/bos/operators/filters/filters.py
- src/bos/operators/utils/clients/cfs.py
CSM 1.6 backport of https://github.com/Cray-HPE/bos/pull/254
> CASMCMS-8941: Break up large CFS component queries to avoid failures

- CHANGELOG.md
- src/bos/operators/session_setup.py
CSM 1.,6 backport of https://github.com/Cray-HPE/bos/pull/259
> CASMCMS-8944: Reduce superfluous S3 calls during BOSv2 session creation

- CHANGELOG.md
- src/bos/operators/actual_state_cleanup.py
- src/bos/operators/base.py
- src/bos/operators/power_on.py
- src/bos/operators/power_operator_base.py
- src/bos/operators/session_setup.py
- src/bos/operators/utils/clients/bos/base.py
- src/bos/operators/utils/clients/bos/options.py
- src/bos/operators/utils/clients/bos/sessions_status.py
- src/bos/operators/utils/clients/bss.py
- src/bos/operators/utils/clients/capmc.py
- src/bos/operators/utils/clients/cfs.py
- src/bos/operators/utils/clients/hsm.py
- src/bos/operators/utils/rootfs/cpss3.py
- src/bos/server/controllers/v2/base.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/controllers/v2/healthz.py
- src/bos/server/controllers/v2/options.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
This PR contains no functional changes to BOS. Most of what it does is to add new logging statements, although in a few cases it modifies existing logging statements, usually to make them consistent with other similar ones. Most of these statements are DEBUG, so they will not show up ordinarily. The intention is to make it easier to trace execution to debug problems (like I am doing on the UKMet systems).
I have tested this on wasp to verify that no unexpected problems were introduced, and that the expected logging is happening.
> CASMCMS-8949: Improve BOS v2 logging

- CHANGELOG.md
- src/bos/operators/actual_state_cleanup.py
- src/bos/operators/base.py
- src/bos/operators/power_on.py
- src/bos/operators/session_setup.py
- src/bos/operators/utils/clients/bos/base.py
- src/bos/operators/utils/clients/bos/options.py
- src/bos/operators/utils/clients/bos/sessions_status.py
- src/bos/operators/utils/clients/bss.py
- src/bos/operators/utils/clients/cfs.py
- src/bos/operators/utils/clients/hsm.py
- src/bos/operators/utils/rootfs/cpss3.py
- src/bos/server/controllers/v2/base.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/controllers/v2/healthz.py
- src/bos/server/controllers/v2/options.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
Backport of https://github.com/Cray-HPE/bos/pull/276
> CASMCMS-8949: Improve BOS v2 debug logging

- CHANGELOG.md
- src/bos/operators/utils/clients/cfs.py
Backport of https://github.com/Cray-HPE/bos/pull/289
> CASMCMS-8954: Make BOS more efficient when patching CFS components

- CHANGELOG.md
- src/bos/operators/filters/filters.py
- src/bos/operators/status.py
- src/bos/operators/utils/clients/cfs.py
Backport of https://github.com/Cray-HPE/bos/pull/292
> CASMCMS-8953: Use CFS v3 instead of v2

- CHANGELOG.md
- api/openapi.yaml.in
Backport of https://github.com/Cray-HPE/bos/pull/296
> CASMCMS-8957: Update BOS v1 API spec to confirm with how BOA actually uses it

- CHANGELOG.md
- src/bos/common/utils.py
- src/bos/operators/base.py
- src/bos/operators/configuration.py
- src/bos/operators/power_on.py
- src/bos/operators/power_operator_base.py
- src/bos/operators/session_setup.py
- src/bos/operators/utils/boot_image_metadata/s3_boot_image_metadata.py
- src/bos/operators/utils/clients/bos/base.py
- src/bos/operators/utils/clients/bos/options.py
- src/bos/operators/utils/clients/bss.py
- src/bos/operators/utils/clients/capmc.py
- src/bos/operators/utils/clients/cfs.py
- src/bos/operators/utils/clients/hsm.py
- src/bos/operators/utils/clients/s3.py
- src/bos/operators/utils/rootfs/cpss3.py
- src/bos/reporter/components/state.py
- src/bos/reporter/node_identity.py
- src/bos/reporter/status_reporter/__main__.py
- src/bos/server/controllers/v2/base.py
- src/bos/server/controllers/v2/boot_set.py
- src/bos/server/controllers/v2/components.py
- src/bos/server/controllers/v2/healthz.py
- src/bos/server/controllers/v2/options.py
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
- src/bos/server/redis_db_utils.py
Backports of CASMCMS-8997 and CASMCMS-8998 to CSM 1.4
Plus fixes for CASMCMS-8995 and CASMCMS-8996.
I tested this on wasp.
> Release 2.0.38 for CSM 1.4

- CHANGELOG.md
- config/uwsgi.ini
- kubernetes/cray-bos/values.yaml.in
- src/bos/operators/power_on.py
- src/bos/operators/utils/clients/pcs.py
- src/bos/operators/utils/clients/s3.py
- src/bos/reporter/components/state.py
- src/bos/reporter/proc_cmdline.py
- src/bos/server/controllers/v1/session.py
- src/bos/server/controllers/v1/sessiontemplate.py
- src/bos/server/controllers/v2/boot_set.py
- src/bos/server/dbclient.py
- src/bos/server/dbs/boot_artifacts.py
- src/bos/server/migrations.py
Backport of the relevant portions of https://github.com/Cray-HPE/bos/pull/314 to CSM 1.5
> Release 2.10.17 for CSM 1.5

- CHANGELOG.md
- config/uwsgi.ini
- kubernetes/cray-bos/values.yaml.in
- src/bos/operators/power_on.py
- src/bos/operators/utils/clients/pcs.py
- src/bos/operators/utils/clients/s3.py
- src/bos/reporter/components/state.py
- src/bos/reporter/proc_cmdline.py
- src/bos/server/controllers/v2/boot_set.py
- src/bos/server/dbs/boot_artifacts.py
- src/bos/server/migrations.py
Backports of relevant parts of https://github.com/Cray-HPE/bos/pull/314 to CSM 1.6
> CASMTRIAGE-6993: Address BOS OOMKill issues at scale

- CHANGELOG.md
- src/bos/operators/utils/clients/s3.py
CSM 1.5 PR for https://github.com/Cray-HPE/bos/pull/321
> CASMCMS-9015: Instantiate S3 client in a thread-safe manner

- CHANGELOG.md
- constraints.txt.in
> CASMCMS-9019: Bump certifi version to resolve CVE

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/operators/base.py
- src/bos/operators/discovery.py
- src/bos/operators/session_setup.py
- src/bos/operators/status.py
- src/bos/operators/utils/clients/bos/options.py
- src/bos/reporter/client.py
- src/bos/server/controllers/v2/options.py
Backport of https://github.com/Cray-HPE/bos/pull/339 for CSM 1.5
See primary [BOS source PR](https://github.com/Cray-HPE/bos/pull/339) for more details.
All PRs:
BOS:
CSM 1.4: https://github.com/Cray-HPE/bos/pull/339
CSM 1.5: https://github.com/Cray-HPE/bos/pull/340
CSM 1.6: https://github.com/Cray-HPE/bos/pull/341
CLI:
CSM 1.4: https://github.com/Cray-HPE/craycli/pull/155
CSM 1.5: https://github.com/Cray-HPE/craycli/pull/156
CSM 1.6: https://github.com/Cray-HPE/craycli/pull/157
> CASMTRIAGE-7147: Create max_component_batch_size option

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/operators/utils/clients/bos/options.py
- src/bos/server/controllers/v2/options.py
- src/bos/server/controllers/v2/sessions.py
Backport of https://github.com/Cray-HPE/bos/pull/346 for CSM 1.5
> CASMCMS-9067: Add session_limit_required option

- CHANGELOG.md
- Dockerfile
- api/openapi.yaml.in
- src/bos/server/controllers/v2/sessions.py
- src/bos/server/controllers/v2/sessiontemplates.py
- src/bos/server/utils.py
This PR combines other PRs that were reviewed individually
> CASMCMS-8694: Enforce BOS API spec

- CHANGELOG.md
- api/openapi.yaml.in
- constraints.txt
- src/bos/operators/utils/clients/bos/options.py
- src/bos/operators/utils/clients/cfs.py
- src/bos/server/controllers/v2/options.py
Backport CASMCMS-9162 for CSM 1.4
> CASMCMS-9162: Add cfs_read_timeout option

- CHANGELOG.md
- api/openapi.yaml.in
- src/bos/common/clients/api_client.py
- src/bos/common/clients/api_client_with_timeout_option.py
- src/bos/common/clients/bss/client.py
- src/bos/common/clients/cfs/client.py
- src/bos/common/clients/hsm/client.py
- src/bos/common/clients/pcs/client.py
- src/bos/common/options.py
- src/bos/server/controllers/v2/boot_set/ims.py
https://github.com/Cray-HPE/bos/pull/418 for CSM 1.7
> CASMCMS-9242: Add BOS options: bss_read_timeout, ims_read_timeout, hsm_read_timeout, pcs_read_timeout

- CHANGELOG.md
- src/bos/common/utils.py
- src/bos/operators/power_on.py
CSM 1.7 "back"port of https://github.com/Cray-HPE/bos/pull/425
> CASMCMS-9255: Improve kernel path parsing; fix bug logging image tagging errors

- CHANGELOG.md
- src/bos/server/controllers/v2/sessiontemplates.py
CSM 1.6 backport of https://github.com/Cray-HPE/bos/pull/431
> CASMCMS-9270: Properly handle being asked to validate nonexistent session template

- CHANGELOG.md
- constraints.txt.in
- src/bos/operators/base.py
- src/bos/operators/configuration.py
- src/bos/operators/filters/__init__.py
- src/bos/operators/filters/base.py
- src/bos/operators/filters/filters.py
- src/bos/operators/session_setup.py
- src/bos/operators/status.py
A mild refactoring of the filters module, including type annotating it properly.
> CASMCMS-9297: Improve Python type annotations in filters module

- CHANGELOG.md
- kubernetes/cray-bos/templates/db.yaml
CASMCMS-9320:Add app.kubernetes.io/instance: cray-bos label to cray-bos-db pod
Deployed cray-bos on mug. Now the label is assigned to cray-bos-db pod …
> CASMCMS-9320:Add app.kubernetes.io/instance: cray-bos label to cray-bos-db pod

- CHANGELOG.md
- src/bos/server/__main__.py
- src/bos/server/options.py
- src/bos/server/redis_db_utils/dbwrapper.py
This corrects a minor bug causing some ugly log messages occasionally when the BOS chart is first deployed.
> CASMCMS-9356: Fix how OptionsData class handles initialization

- CHANGELOG.md
- src/bos/common/utils.py
CSM 1.6 backport of https://github.com/Cray-HPE/bos/pull/481
> CASMCMS-9357: Made compact_response_text more efficient

- CHANGELOG.md
- src/bos/common/utils.py
- src/bos/operators/base.py
- src/bos/operators/filters/base.py
- src/bos/operators/power_on.py
- src/bos/operators/session_setup.py
- src/bos/operators/utils/clients/bos/base.py
- src/bos/operators/utils/clients/bos/options.py
- src/bos/operators/utils/clients/bos/sessions_status.py
- src/bos/server/controllers/v2/boot_set/ims.py
CSM 1.6 backport of https://github.com/Cray-HPE/bos/pull/485
> CASMCMS-9353: Improve exception logging

- CHANGELOG.md
- src/bos/server/options.py
This adds explicit type annotations to the `OptionsData` class in `server/options.py`, to resolve `mypy` concerns.
> CASMCMS-9416: Resolve type annotation issues in server/options.py

- CHANGELOG.md
- src/bos/common/clients/hsm/inventory.py
- src/bos/common/clients/s3/boot_image_meta_data.py
- src/bos/common/clients/s3/s3.py
- src/bos/operators/base.py
- src/bos/operators/session_setup.py
- src/bos/operators/utils/liveness/timestamp.py
I tested these changes on mug, including using the updated `cmsdev` test tool with @kumarrahul04 's latest BOS additions.
> CASMCMS-9430: Modify select @property decorators into @cached_property, for improved performance
